#!/usr/bin/env python3
"""create_gitlab_mr — Create a GitLab MR in releng/konflux-release-data with the exception YAML.

PUBLIC API:
    detect_component_type(components) -> str  [line 537]
    get_target_file(component_type, environment, is_self_service) -> str  [line 545]
    generate_exception_yaml(rule, components, effective_until, reference_url, rhoaieng_url, rhoai_version, is_self_service, is_weekday_restriction, image_ref, reference_title, spreadsheet_url) -> str  [line 558]
    remove_exception_from_policy_file(file_path, rule, effective_until, components) -> dict  [line 690]
    apply_exception_to_policy_file(file_path, yaml_block, is_self_service, rule, components, effective_until) -> dict  [line 766]
    append_to_policy_file(file_path, yaml_block, is_self_service) -> None  [line 833]
    create_mr(rule, components, effective_until, reference_url, rhoaieng_url, rhoai_version, environment, is_self_service, is_weekday_restriction, image_ref, reference_title, spreadsheet_url, vendor_tag, exception_risk, exception_remediation, policy_file, dry_run) -> dict  [line 847]
    update_mr(branch_name, rule, components, effective_until, reference_url, rhoaieng_url, rhoai_version, environment, is_self_service, is_weekday_restriction, image_ref, reference_title, spreadsheet_url, vendor_tag, exception_risk, exception_remediation, policy_file, dry_run) -> dict  [line 1070]
    update_consolidated_mr(branch_name, rule, version_specs, reference_url, rhoaieng_url, environment, is_self_service, reference_title, spreadsheet_url, vendor_tag, exception_risk, exception_remediation, policy_file, dry_run) -> dict  [line 1274]
    create_consolidated_mr(rule, version_specs, reference_url, rhoaieng_url, environment, is_self_service, reference_title, spreadsheet_url, vendor_tag, exception_risk, exception_remediation, policy_file, dry_run) -> dict  [line 1464]
    remove_expired_mr(rule, effective_until, rhoai_version, environment, components, reference_url, clone_dir, policy_file, dry_run) -> dict  [line 1775]
    modernize_exception_mr(rule, old_effective_until, version_specs, environment, reference_url, rhoaieng_url, old_components, policy_file, spreadsheet_url, vendor_tag, exception_risk, exception_remediation, dry_run) -> dict  [line 1963]
    parse_args() -> argparse.Namespace  [line 2242]
    main() -> int  [line 2304]

INTERNAL SECTIONS:
    Main: _build_commit_message, _build_commit_message_extend, _build_commit_message_remove, _build_mr_body, _build_mr_title, ... (+6 more)
    AmbiguousPolicyFileError: _get_application_slug, _resolve_policy_file, _resolve_self_service_file, _get_conforma_policy_dir, _get_discovered_ec_files, ... (+10 more)

DEPENDENCIES: argparse, getpass, gitlab_ops, json, konflux_environment, os, pathlib, platform, posixpath, re

"""

from __future__ import annotations

import _setup_env  # noqa: F401 -- adds shared scripts/ to sys.path

import argparse
import getpass
import json
import os
import platform
import posixpath
import re
import subprocess
import sys
import tempfile
from pathlib import Path

import gitlab_ops
import konflux_environment

konflux_environment.require("gitlab")

GITLAB_HOST = os.environ.get("GITLAB_HOST", "")
GITLAB_PROJECT = os.environ.get("GITLAB_PROJECT", "releng/konflux-release-data")
DEFAULT_BRANCH = "main"
PROVENANCE_REPO = "opendatahub-io/aiops-infra"
PROVENANCE_SKILL = "conforma-exception-ai-skill"

_SKILL_DIR = Path(__file__).resolve().parent.parent
WORK_DIR = _SKILL_DIR / ".work"


def _build_commit_message(
    rule: str,
    components: list[str],
    rhoai_version: str,
    effective_until: str,
    rhoaieng_url: str | None = None,
    reference_url: str | None = None,
    spreadsheet_url: str | None = None,
    target_file: str | None = None,
    exception_risk: str | None = None,
    exception_remediation: str | None = None,
) -> str:
    """Build a structured, multi-line commit message with provenance."""
    subject = f"Add conforma exception: {rule} ({rhoai_version})"

    lines = [
        subject,
        "",
        "Exception details:",
        f"  Rule: {rule}",
        f"  RHOAI version: {rhoai_version}",
        f"  Effective until: {effective_until}",
        f"  Components: {', '.join(components)}",
    ]

    if target_file:
        lines.append(f"  Policy file: {target_file}")

    if exception_risk:
        lines.append(f"  Risk: {exception_risk}")
    if exception_remediation:
        lines.append(f"  Remediation: {exception_remediation}")

    lines.append("")

    if rhoaieng_url:
        lines.append(f"RHOAIENG: {rhoaieng_url}")
    if reference_url:
        lines.append(f"Reference: {reference_url}")
    if spreadsheet_url:
        lines.append(f"Spreadsheet: {spreadsheet_url}")

    if rhoaieng_url or reference_url or spreadsheet_url:
        lines.append("")

    lines.extend(
        [
            "---",
            f"Generated by: {PROVENANCE_SKILL}",
            f"Source: https://github.com/{PROVENANCE_REPO}",
            f"User: {getpass.getuser()}@{platform.node()}",
        ]
    )

    return "\n".join(lines)


def _build_commit_message_extend(
    rule: str,
    components: list[str],
    rhoai_version: str,
    effective_until: str,
    rhoaieng_url: str | None = None,
    reference_url: str | None = None,
    spreadsheet_url: str | None = None,
    target_file: str | None = None,
    exception_risk: str | None = None,
    exception_remediation: str | None = None,
) -> str:
    """Build a commit message for extending an existing exception's effectiveUntil."""
    subject = f"Extend conforma exception: {rule} ({rhoai_version})"

    lines = [
        subject,
        "",
        "Extended existing exception (effectiveUntil date updated):",
        f"  Rule: {rule}",
        f"  RHOAI version: {rhoai_version}",
        f"  New effectiveUntil: {effective_until}",
        f"  Components: {', '.join(components)}",
    ]

    if target_file:
        lines.append(f"  Policy file: {target_file}")
    if exception_risk:
        lines.append(f"  Risk: {exception_risk}")
    if exception_remediation:
        lines.append(f"  Remediation: {exception_remediation}")

    lines.append("")

    if rhoaieng_url:
        lines.append(f"RHOAIENG: {rhoaieng_url}")
    if reference_url:
        lines.append(f"Reference: {reference_url}")
    if spreadsheet_url:
        lines.append(f"Spreadsheet: {spreadsheet_url}")

    if rhoaieng_url or reference_url or spreadsheet_url:
        lines.append("")

    lines.extend(
        [
            "---",
            f"Generated by: {PROVENANCE_SKILL}",
            f"Source: https://github.com/{PROVENANCE_REPO}",
            f"User: {getpass.getuser()}@{platform.node()}",
        ]
    )

    return "\n".join(lines)


def _build_commit_message_remove(
    rule: str,
    rhoai_version: str,
    effective_until: str,
    components: list[str] | None = None,
    reference_url: str | None = None,
    target_file: str | None = None,
) -> str:
    """Build a commit message for removing an expired exception."""
    subject = f"Remove expired conforma exception: {rule} ({rhoai_version})"

    lines = [
        subject,
        "",
        "Removed expired exception:",
        f"  Rule: {rule}",
        f"  RHOAI version: {rhoai_version}",
        f"  Expired effectiveUntil: {effective_until}",
    ]

    if components:
        lines.append(f"  Components: {', '.join(components)}")
    else:
        lines.append("  Components: (unscoped, all components)")

    if target_file:
        lines.append(f"  Policy file: {target_file}")

    lines.append("")

    if reference_url:
        lines.append(f"Reference: {reference_url}")
        lines.append("")

    lines.extend(
        [
            "---",
            f"Generated by: {PROVENANCE_SKILL}",
            f"Source: https://github.com/{PROVENANCE_REPO}",
            f"User: {getpass.getuser()}@{platform.node()}",
        ]
    )

    return "\n".join(lines)


def _build_mr_body(
    rule: str,
    components: list[str],
    rhoai_version: str,
    effective_until: str,
    rhoaieng_url: str | None = None,
    reference_url: str | None = None,
    spreadsheet_url: str | None = None,
    target_file: str | None = None,
) -> str:
    """Build a markdown-formatted MR description for GitLab rendering."""
    lines = [
        f"## Exception: `{rule}` for `{rhoai_version}`",
        "",
        "| Field | Value |",
        "|-------|-------|",
        f"| **Rule** | `{rule}` |",
        f"| **RHOAI version** | `{rhoai_version}` |",
        f"| **Effective until** | `{effective_until}` |",
        f"| **Policy file** | `{target_file or 'N/A'}` |",
        "",
        "### Components",
        "",
    ]
    for comp in components:
        lines.append(f"- `{comp}`")

    lines.append("")

    if rhoaieng_url or reference_url or spreadsheet_url:
        lines.append("### References")
        lines.append("")
        if rhoaieng_url:
            lines.append(f"- **RHOAIENG**: {rhoaieng_url}")
        if reference_url:
            lines.append(f"- **PSX/Reference**: {reference_url}")
        if spreadsheet_url:
            lines.append(f"- **Spreadsheet**: {spreadsheet_url}")
        lines.append("")

    lines.extend(
        [
            "---",
            "",
            f"*Generated by `{PROVENANCE_SKILL}` | "
            f"[source](https://github.com/{PROVENANCE_REPO}) | "
            f"`{getpass.getuser()}@{platform.node()}`*",
        ]
    )

    return "\n".join(lines)


def _build_mr_title(
    rule: str, rhoai_version: str, environment: str, vendor_tag: str | None = None
) -> str:
    """Build the MR title, including vendor tag and environment prefix."""
    env_prefix = f"[{environment}] " if environment else ""
    title = f"{env_prefix}[RHOAI] Conforma exception: {rule} for {rhoai_version}"
    if vendor_tag:
        title = f"[{vendor_tag}] {title}"
    return title


def _build_mr_title_consolidated(
    rule: str, version_specs: list[dict], environment: str, vendor_tag: str | None = None
) -> str:
    """Build MR title for a consolidated (multi-version) exception MR."""
    versions = [s["version"] for s in version_specs]
    if len(versions) == 1:
        version_str = versions[0]
    else:
        version_str = f"{versions[0]}..{versions[-1]}"
    env_prefix = f"[{environment}] " if environment else ""
    title = f"{env_prefix}[RHOAI] Conforma exception: {rule} for {version_str}"
    if vendor_tag:
        title = f"[{vendor_tag}] {title}"
    return title


def _build_commit_message_consolidated(
    rule: str,
    version_specs: list[dict],
    rhoaieng_url: str | None = None,
    reference_url: str | None = None,
    spreadsheet_url: str | None = None,
    target_file: str | None = None,
    exception_risk: str | None = None,
    exception_remediation: str | None = None,
) -> str:
    """Build commit message for a consolidated MR covering multiple RHOAI versions."""
    versions = [s["version"] for s in version_specs]
    subject = f"Add conforma exception: {rule} ({', '.join(versions)})"

    lines = [
        subject,
        "",
        "Exception details:",
        f"  Rule: {rule}",
    ]
    if target_file:
        lines.append(f"  Policy file: {target_file}")
    if exception_risk:
        lines.append(f"  Risk: {exception_risk}")
    if exception_remediation:
        lines.append(f"  Remediation: {exception_remediation}")
    lines.append("")

    for spec in version_specs:
        lines.append(f"  {spec['version']}:")
        lines.append(f"    Components: {', '.join(spec['components'])}")
        lines.append(f"    Effective until: {spec['effective_until']}")
        lines.append("")

    if rhoaieng_url:
        lines.append(f"RHOAIENG: {rhoaieng_url}")
    if reference_url:
        lines.append(f"Reference: {reference_url}")
    if spreadsheet_url:
        lines.append(f"Spreadsheet: {spreadsheet_url}")

    if rhoaieng_url or reference_url or spreadsheet_url:
        lines.append("")

    lines.extend(
        [
            "---",
            f"Generated by: {PROVENANCE_SKILL}",
            f"Source: https://github.com/{PROVENANCE_REPO}",
            f"User: {getpass.getuser()}@{platform.node()}",
        ]
    )

    return "\n".join(lines)


def _build_mr_body_consolidated(
    rule: str,
    version_specs: list[dict],
    rhoaieng_url: str | None = None,
    reference_url: str | None = None,
    spreadsheet_url: str | None = None,
    target_file: str | None = None,
) -> str:
    """Build MR description for a consolidated (multi-version) exception MR."""
    versions = [s["version"] for s in version_specs]
    lines = [
        f"## Exception: `{rule}` for {', '.join(f'`{v}`' for v in versions)}",
        "",
        "| Field | Value |",
        "|-------|-------|",
        f"| **Rule** | `{rule}` |",
        f"| **RHOAI versions** | {', '.join(f'`{v}`' for v in versions)} |",
        f"| **Policy file** | `{target_file or 'N/A'}` |",
        "",
    ]

    for spec in version_specs:
        lines.append(f"### `{spec['version']}`")
        lines.append("")
        lines.append(f"**Effective until**: `{spec['effective_until']}`")
        lines.append("")
        lines.append("**Components**:")
        for comp in spec["components"]:
            lines.append(f"- `{comp}`")
        lines.append("")

    if rhoaieng_url or reference_url or spreadsheet_url:
        lines.append("### References")
        lines.append("")
        if rhoaieng_url:
            lines.append(f"- **RHOAIENG**: {rhoaieng_url}")
        if reference_url:
            lines.append(f"- **PSX/Reference**: {reference_url}")
        if spreadsheet_url:
            lines.append(f"- **Spreadsheet**: {spreadsheet_url}")
        lines.append("")

    lines.extend(
        [
            "---",
            "",
            f"*Generated by `{PROVENANCE_SKILL}` | "
            f"[source](https://github.com/{PROVENANCE_REPO}) | "
            f"`{getpass.getuser()}@{platform.node()}`*",
        ]
    )

    return "\n".join(lines)


def _get_gitlab_token() -> str | None:
    """Retrieve the GitLab auth token for GITLAB_HOST.

    Resolution order (via gitlab_ops.discover_token):
      1. GITLAB_TOKEN environment variable
      2. ~/.config/glab-cli/config.yml (host-specific token)
    Falls back to conforma-specific token file if shared ops can't find one.
    """
    token = gitlab_ops.discover_token(GITLAB_HOST)
    if token:
        return token
    return os.environ.get("GITLAB_TOKEN")


def _get_authenticated_repo_url(project: str = GITLAB_PROJECT) -> str:
    """Return a plain HTTPS clone URL (no embedded credentials)."""
    return f"https://{GITLAB_HOST}/{project}.git"


def _validate_repo_relative_path(path_str: str, context: str = "policy file") -> str:
    """Normalize a repo-relative path and reject any that would escape the repo root.

    Prevents path traversal via absolute paths or ``..`` segments that resolve
    outside the repository checkout directory.
    """
    normalized = posixpath.normpath(path_str)
    if normalized.startswith("/") or normalized.startswith(".."):
        raise ValueError(
            f"Unsafe {context} path {path_str!r}: "
            f"resolved to {normalized!r} which is not repo-relative"
        )
    return normalized


_KONFLUX_CLUSTER_DOMAIN = os.environ.get("KONFLUX_CLUSTER_DOMAIN", "")
_CONFORMA_POLICY_DIR = os.environ.get(
    "KONFLUX_CONFORMA_POLICY_DIR",
    f"config/{_KONFLUX_CLUSTER_DOMAIN}/product/EnterpriseContractPolicy" if _KONFLUX_CLUSTER_DOMAIN else "",
)


class AmbiguousPolicyFileError(Exception):
    """Raised when multiple policy files match and no application slug disambiguates."""

    def __init__(self, component_type: str, environment: str, candidates: list[str]):
        self.component_type = component_type
        self.environment = environment
        self.candidates = candidates
        super().__init__(
            f"Multiple policy files match {component_type}-*-{environment}.yaml: "
            f"{', '.join(candidates)}. "
            f"Set KONFLUX_APPLICATION_SLUG in ~/.conforma/.env (or via Konflux tenant env discovery) "
            f"to disambiguate, or pass --policy-file explicitly."
        )


def _get_application_slug() -> str | None:
    """Get the application slug from env (set by Konflux tenant env discovery or ~/.conforma/.env).

    The application slug identifies which set of policy files belongs to the
    current application (e.g. 'rhoai' matches registry-rhoai-prod.yaml).
    """
    return os.environ.get("KONFLUX_APPLICATION_SLUG") or None


def _resolve_policy_file(component_type: str, environment: str, discovered_files: list[str] | None = None) -> str:
    """Resolve the target policy file, filtered by application slug.

    Resolution order:
      1. If KONFLUX_APPLICATION_SLUG is set, match exactly {type}-{slug}-{env}.yaml
      2. If no slug, match {type}-*-{env}.yaml; raise if multiple
      3. Fall back to glob pattern if no discovered files
    """
    conforma_policy_dir = _get_conforma_policy_dir()
    if discovered_files:
        prefix = f"{component_type}-"
        suffix = f"-{environment}.yaml"
        type_env_matches = [f for f in discovered_files if f.startswith(prefix) and f.endswith(suffix)]

        app_slug = _get_application_slug()
        if app_slug:
            exact = f"{component_type}-{app_slug}-{environment}.yaml"
            if exact in type_env_matches:
                return f"{conforma_policy_dir}/{exact}"
            if type_env_matches:
                return f"{conforma_policy_dir}/{type_env_matches[0]}"

        if len(type_env_matches) == 1:
            return f"{conforma_policy_dir}/{type_env_matches[0]}"
        if len(type_env_matches) > 1:
            raise AmbiguousPolicyFileError(component_type, environment, type_env_matches)

    return f"{conforma_policy_dir}/{component_type}-*-{environment}.yaml"


def _resolve_self_service_file(component_type: str, environment: str, discovered_files: list[str] | None = None) -> str:
    """Resolve a self-service exception file, filtered by application slug."""
    if discovered_files:
        prefix = f"{component_type}-"
        suffix = f"-{environment}.yaml"
        type_env_matches = [f for f in discovered_files if f.startswith(prefix) and f.endswith(suffix)]

        app_slug = _get_application_slug()
        if app_slug:
            exact = f"{component_type}-{app_slug}-{environment}.yaml"
            if exact in type_env_matches:
                return f"exceptions/{exact}"
            if type_env_matches:
                return f"exceptions/{type_env_matches[0]}"

        if len(type_env_matches) == 1:
            return f"exceptions/{type_env_matches[0]}"
        if len(type_env_matches) > 1:
            raise AmbiguousPolicyFileError(component_type, environment, type_env_matches)

    return f"exceptions/{component_type}-*-{environment}.yaml"


def _get_conforma_policy_dir() -> str:
    """Resolve Conforma policy dir at call time (env may change after import)."""
    val = os.environ.get("KONFLUX_CONFORMA_POLICY_DIR", "")
    if val:
        return val
    domain = os.environ.get("KONFLUX_CLUSTER_DOMAIN", "")
    if domain:
        return f"config/{domain}/product/EnterpriseContractPolicy"
    return _CONFORMA_POLICY_DIR


def _get_discovered_ec_files() -> list[str] | None:
    """Get the list of Conforma policy files from discovery (if available)."""
    raw = os.environ.get("KONFLUX_CONFORMA_POLICY_FILES", "")
    if raw:
        return [f.strip() for f in raw.split(",") if f.strip()]
    return None


def _get_discovered_self_service_files() -> list[str] | None:
    """Get the list of self-service exception files from discovery (if available)."""
    raw = os.environ.get("KONFLUX_SELF_SERVICE_FILES", "")
    if raw:
        return [f.strip() for f in raw.split(",") if f.strip()]
    return None


def detect_component_type(components: list[str]) -> str:
    """Detect if components are FBC or registry type."""
    for comp in components:
        if "fbc" in comp.lower():
            return "fbc"
    return "registry"


def get_target_file(component_type: str, environment: str, is_self_service: bool) -> str:
    """Determine the target policy file path using discovery or pattern matching."""
    if is_self_service:
        path = _resolve_self_service_file(
            component_type, environment, _get_discovered_self_service_files()
        )
    else:
        path = _resolve_policy_file(
            component_type, environment, _get_discovered_ec_files()
        )
    return _validate_repo_relative_path(path)


def generate_exception_yaml(
    rule: str,
    components: list[str],
    effective_until: str,
    reference_url: str,
    rhoaieng_url: str | None,
    rhoai_version: str,
    is_self_service: bool,
    is_weekday_restriction: bool = False,
    image_ref: str | None = None,
    reference_title: str | None = None,
    spreadsheet_url: str | None = None,
) -> str:
    """Generate the YAML exception block to append.

    Components must be Konflux component names (with -vX-Y suffix), NOT container
    image names (which end in -rhel9/-ubi9). validate_inputs.py enforces this.
    """
    if is_self_service and is_weekday_restriction and image_ref:
        return f"- value: {rule}\n  imageRef: {image_ref}\n"

    if is_self_service:
        lines = [f"- value: {rule}"]
        lines.append("  componentNames:")
        for comp in components:
            lines.append(f"    - {comp}")
        if effective_until:
            lines.append(f'  effectiveUntil: "{effective_until}"')
        return "\n".join(lines) + "\n"

    indent = "          "
    lines = []
    if rhoaieng_url:
        lines.append(f"{indent}# {rhoaieng_url}")
    lines.append(f"{indent}# impacted versions: {rhoai_version}")
    if spreadsheet_url:
        lines.append(f"{indent}# spreadsheet: {spreadsheet_url}")
    lines.append(f"{indent}- value: {rule}")
    lines.append(f"{indent}  componentNames:")
    for comp in components:
        lines.append(f"{indent}    - {comp}")
    lines.append(f'{indent}  effectiveUntil: "{effective_until}"')
    if reference_title:
        lines.append(f"{indent}  reference: {reference_url}  # {reference_title}")
    else:
        lines.append(f"{indent}  reference: {reference_url}")
    return "\n".join(lines) + "\n"


def _find_existing_exceptions(content: str, rule: str, indent: str = "          ") -> list[dict]:
    """Find existing exception blocks for a given rule in the policy file content.

    Returns a list of dicts with:
      - start: line index where the block starts (the `- value:` line)
      - end: line index where the block ends (exclusive)
      - has_component_names: whether the block uses componentNames
      - component_names: list of component names (empty if not used)
      - image_url: imageUrl value if present (empty string if not)
      - effective_until_line: line index of the effectiveUntil line (or None)
      - effective_until_value: current effectiveUntil value (or None)
    """
    lines = content.split("\n")
    results = []
    value_pattern = re.compile(rf"^{re.escape(indent)}- value:\s*(.+)$")
    i = 0
    while i < len(lines):
        match = value_pattern.match(lines[i])
        if match and match.group(1).strip() == rule:
            block_start = i
            block_info: dict = {
                "start": block_start,
                "end": block_start + 1,
                "has_component_names": False,
                "component_names": [],
                "image_url": "",
                "effective_until_line": None,
                "effective_until_value": None,
            }
            i += 1
            while i < len(lines):
                line = lines[i]
                if not line.strip() or value_pattern.match(line):
                    break
                if line.startswith(f"{indent}#"):
                    break
                if line.strip().startswith("- value:"):
                    break
                if "componentNames:" in line:
                    block_info["has_component_names"] = True
                    i += 1
                    while i < len(lines) and lines[i].strip().startswith("- "):
                        comp = lines[i].strip().lstrip("- ").strip()
                        block_info["component_names"].append(comp)
                        block_info["end"] = i + 1
                        i += 1
                    continue
                if "imageUrl:" in line:
                    iu_match = re.search(r'imageUrl:\s*"?([^"]+)"?', line)
                    if iu_match:
                        block_info["image_url"] = iu_match.group(1).strip()
                if "effectiveUntil:" in line:
                    block_info["effective_until_line"] = i
                    eu_match = re.search(r'effectiveUntil:\s*"?([^"]+)"?', line)
                    if eu_match:
                        block_info["effective_until_value"] = eu_match.group(1).strip()
                block_info["end"] = i + 1
                i += 1
            results.append(block_info)
        else:
            i += 1
    return results


def _update_effective_until_in_content(content: str, line_idx: int, new_effective_until: str) -> str:
    """Replace the effectiveUntil value at the given line index."""
    lines = content.split("\n")
    old_line = lines[line_idx]
    new_line = re.sub(
        r'effectiveUntil:\s*"[^"]*"',
        f'effectiveUntil: "{new_effective_until}"',
        old_line,
    )
    if new_line == old_line:
        new_line = re.sub(
            r"effectiveUntil:\s*\S+",
            f'effectiveUntil: "{new_effective_until}"',
            old_line,
        )
    lines[line_idx] = new_line
    return "\n".join(lines)


def remove_exception_from_policy_file(
    file_path: Path,
    rule: str,
    effective_until: str,
    components: list[str] | None = None,
) -> dict:
    """Remove an expired exception block and its preceding comment header.

    The block is identified by matching rule + effectiveUntil + components.
    For unscoped exceptions (no componentNames), only rule + effectiveUntil
    are needed.

    Returns:
        {"action": "removed", "detail": "...", "lines_removed": N}
        or {"action": "not_found", "detail": "..."}
    """
    content = file_path.read_text(encoding="utf-8")
    indent = "          "
    existing = _find_existing_exceptions(content, rule, indent)

    target_block = None
    for block in existing:
        if block["effective_until_value"] != effective_until:
            continue
        if components and block["has_component_names"]:
            if sorted(block["component_names"]) == sorted(components):
                target_block = block
                break
        elif not components and not block["has_component_names"]:
            target_block = block
            break
        elif components and not block["has_component_names"]:
            target_block = block
            break

    if not target_block:
        return {
            "action": "not_found",
            "detail": (
                f"No matching exception block found for rule={rule}, "
                f"effectiveUntil={effective_until}, components={components}"
            ),
        }

    lines = content.split("\n")
    block_start = target_block["start"]
    block_end = target_block["end"]

    comment_start = block_start
    i = block_start - 1
    while i >= 0:
        stripped = lines[i].strip()
        if stripped.startswith("#") and lines[i].startswith(indent):
            comment_start = i
            i -= 1
        elif stripped == "":
            i -= 1
        else:
            break

    del lines[comment_start:block_end]
    while comment_start < len(lines) and lines[comment_start].strip() == "":
        del lines[comment_start]

    file_path.write_text("\n".join(lines), encoding="utf-8")
    lines_removed = block_end - comment_start
    return {
        "action": "removed",
        "detail": (
            f"Removed expired exception for {rule} "
            f"(lines {comment_start + 1}-{block_end}, effectiveUntil={effective_until})"
        ),
        "lines_removed": lines_removed,
    }


def apply_exception_to_policy_file(
    file_path: Path,
    yaml_block: str,
    is_self_service: bool,
    rule: str,
    components: list[str],
    effective_until: str,
) -> dict:
    """Apply exception to the policy file with deduplication logic.

    Returns a dict with:
      - action: "appended" | "extended" | "appended_new_style"
      - detail: human-readable description of what was done
    """
    content = file_path.read_text(encoding="utf-8")

    if is_self_service:
        if content.rstrip().endswith("---"):
            content = content.rstrip() + "\n"
        content += yaml_block
        file_path.write_text(content, encoding="utf-8")
        return {"action": "appended", "detail": "Appended self-service exception"}

    existing = _find_existing_exceptions(content, rule)

    if not existing:
        content = content.rstrip() + "\n" + yaml_block
        file_path.write_text(content, encoding="utf-8")
        return {"action": "appended", "detail": "No existing exception for this rule; appended new block"}

    sorted_components = sorted(components)
    for exc in existing:
        if exc["has_component_names"]:
            if sorted(exc["component_names"]) == sorted_components:
                if exc["effective_until_line"] is not None:
                    content = _update_effective_until_in_content(content, exc["effective_until_line"], effective_until)
                    file_path.write_text(content, encoding="utf-8")
                    old_date = exc["effective_until_value"] or "unknown"
                    return {
                        "action": "extended",
                        "detail": (
                            f"Extended existing exception effectiveUntil from "
                            f"{old_date} to {effective_until} "
                            f"(componentNames matched)"
                        ),
                    }

    has_old_style = any(not exc["has_component_names"] for exc in existing)
    if has_old_style:
        content = content.rstrip() + "\n" + yaml_block
        file_path.write_text(content, encoding="utf-8")
        return {
            "action": "appended_new_style",
            "detail": (
                "Old-style exception (no componentNames) found for this rule; "
                "left intact and appended new componentNames-based exception"
            ),
        }

    content = content.rstrip() + "\n" + yaml_block
    file_path.write_text(content, encoding="utf-8")
    return {
        "action": "appended",
        "detail": ("Existing exception found for this rule but with different componentNames; appended new block"),
    }


def append_to_policy_file(file_path: Path, yaml_block: str, is_self_service: bool) -> None:
    """Append the exception block to the target file (deprecated interface)."""
    content = file_path.read_text(encoding="utf-8")

    if is_self_service:
        if content.rstrip().endswith("---"):
            content = content.rstrip() + "\n"
        content += yaml_block
    else:
        content = content.rstrip() + "\n" + yaml_block

    file_path.write_text(content, encoding="utf-8")


def create_mr(
    rule: str,
    components: list[str],
    effective_until: str,
    reference_url: str,
    rhoaieng_url: str | None,
    rhoai_version: str,
    environment: str,
    is_self_service: bool,
    is_weekday_restriction: bool = False,
    image_ref: str | None = None,
    reference_title: str | None = None,
    spreadsheet_url: str | None = None,
    vendor_tag: str | None = None,
    exception_risk: str | None = None,
    exception_remediation: str | None = None,
    policy_file: str | None = None,
    dry_run: bool = False,
) -> dict:
    """Clone repo, append exception, create MR."""
    component_type = detect_component_type(components)
    if policy_file:
        target_file = _validate_repo_relative_path(policy_file, "policy-file argument")
    else:
        target_file = get_target_file(component_type, environment, is_self_service)

    yaml_block = generate_exception_yaml(
        rule=rule,
        components=components,
        effective_until=effective_until,
        reference_url=reference_url,
        rhoaieng_url=rhoaieng_url,
        rhoai_version=rhoai_version,
        is_self_service=is_self_service,
        is_weekday_restriction=is_weekday_restriction,
        image_ref=image_ref,
        reference_title=reference_title,
        spreadsheet_url=spreadsheet_url,
    )

    if dry_run:
        return {
            "status": "dry_run",
            "target_file": target_file,
            "yaml_block": yaml_block,
            "component_type": component_type,
            "mr_url": None,
            "dedup_note": (
                "At execution time, the script will check if an exception for this "
                "rule already exists: if it uses componentNames and they match, "
                "effectiveUntil will be extended in-place; if old-style (no "
                "componentNames), it will be left intact and a new block appended."
            ),
        }

    WORK_DIR.mkdir(parents=True, exist_ok=True)
    workdir = Path(tempfile.mkdtemp(prefix="conforma-exception-mr-", dir=WORK_DIR))
    try:
        clone_dest = str(workdir / "repo")
        repo_url = _get_authenticated_repo_url()
        _run_git(
            [
                "git",
                "clone",
                "--depth=1",
                "--branch",
                DEFAULT_BRANCH,
                "--filter=blob:none",
                "--sparse",
                repo_url,
                clone_dest,
            ],
            timeout=300,
        )
        repo_dir = workdir / "repo"
        policy_dir = str(Path(target_file).parent)
        _run_git(["git", "sparse-checkout", "set", policy_dir], cwd=repo_dir)

        branch_name = _make_branch_name(rule, rhoai_version, components)
        _run_git(["git", "checkout", "-b", branch_name], cwd=repo_dir)

        policy_file = repo_dir / target_file
        if not policy_file.exists():
            return {
                "status": "failed",
                "error": f"Target file not found: {target_file}",
                "target_file": target_file,
                "mr_url": None,
            }

        apply_result = apply_exception_to_policy_file(
            file_path=policy_file,
            yaml_block=yaml_block,
            is_self_service=is_self_service,
            rule=rule,
            components=components,
            effective_until=effective_until,
        )

        action = apply_result["action"]
        if action == "extended":
            commit_msg = _build_commit_message_extend(
                rule=rule,
                components=components,
                rhoai_version=rhoai_version,
                effective_until=effective_until,
                rhoaieng_url=rhoaieng_url,
                reference_url=reference_url,
                spreadsheet_url=spreadsheet_url,
                target_file=target_file,
                exception_risk=exception_risk,
                exception_remediation=exception_remediation,
            )
        else:
            commit_msg = _build_commit_message(
                rule=rule,
                components=components,
                rhoai_version=rhoai_version,
                effective_until=effective_until,
                rhoaieng_url=rhoaieng_url,
                reference_url=reference_url,
                spreadsheet_url=spreadsheet_url,
                target_file=target_file,
                exception_risk=exception_risk,
                exception_remediation=exception_remediation,
            )

        _run_git(["git", "add", target_file], cwd=repo_dir)
        _run_git(["git", "commit", "-m", commit_msg], cwd=repo_dir)
        push_result = subprocess.run(
            ["git", "push", "-u", "origin", branch_name],
            capture_output=True,
            text=True,
            timeout=60,
            cwd=repo_dir,
            env=gitlab_ops.git_env(),
        )

        use_fork = False
        if push_result.returncode != 0:
            fork_url = _ensure_fork(repo_dir)
            if not fork_url:
                return {
                    "status": "failed",
                    "error": (f"Push failed and fork creation failed: {push_result.stderr.strip()}"),
                    "target_file": target_file,
                    "branch": branch_name,
                    "mr_url": None,
                }
            _run_git(["git", "remote", "add", "fork", fork_url], cwd=repo_dir)
            _run_git(["git", "push", "-u", "fork", branch_name], cwd=repo_dir)
            use_fork = True

        mr_title = _build_mr_title(rule, rhoai_version, environment, vendor_tag)
        mr_body = _build_mr_body(
            rule=rule,
            components=components,
            rhoai_version=rhoai_version,
            effective_until=effective_until,
            rhoaieng_url=rhoaieng_url,
            reference_url=reference_url,
            spreadsheet_url=spreadsheet_url,
            target_file=target_file,
        )
        mr_create_args = [
            "mr",
            "create",
            "--title",
            mr_title,
            "--description",
            mr_body,
            "--target-branch",
            DEFAULT_BRANCH,
            "--remove-source-branch",
            "-R",
            f"{GITLAB_HOST}/{GITLAB_PROJECT}",
        ]
        if use_fork:
            mr_create_args.extend(["--head", branch_name])

        mr_result = subprocess.run(
            ["glab", *mr_create_args],
            capture_output=True,
            text=True,
            timeout=30,
            cwd=repo_dir,
        )

        if mr_result.returncode != 0:
            return {
                "status": "failed",
                "error": mr_result.stderr.strip() or mr_result.stdout.strip(),
                "target_file": target_file,
                "branch": branch_name,
                "mr_url": None,
                "use_fork": use_fork,
            }

        mr_url = _extract_mr_url(mr_result.stdout + mr_result.stderr)
        return {
            "status": "created",
            "target_file": target_file,
            "branch": branch_name,
            "mr_url": mr_url,
            "yaml_block": yaml_block,
            "component_type": component_type,
            "use_fork": use_fork,
            "apply_action": apply_result["action"],
            "apply_detail": apply_result["detail"],
        }
    except subprocess.CalledProcessError as exc:
        return {
            "status": "failed",
            "error": f"Git operation failed: {exc.stderr or exc.stdout}",
            "target_file": target_file,
            "mr_url": None,
        }
    finally:
        import shutil

        shutil.rmtree(workdir, ignore_errors=True)


def update_mr(
    branch_name: str,
    rule: str,
    components: list[str],
    effective_until: str,
    reference_url: str,
    rhoaieng_url: str | None,
    rhoai_version: str,
    environment: str,
    is_self_service: bool,
    is_weekday_restriction: bool = False,
    image_ref: str | None = None,
    reference_title: str | None = None,
    spreadsheet_url: str | None = None,
    vendor_tag: str | None = None,
    exception_risk: str | None = None,
    exception_remediation: str | None = None,
    policy_file: str | None = None,
    dry_run: bool = False,
) -> dict:
    """Update an existing MR branch by recreating it from current main.

    Always clones from main first to maintain proper merge-base ancestry,
    then creates the branch, applies the exception, and force-pushes.
    This avoids disconnected-history issues that cause GitLab to show
    hundreds of unrelated file changes in the MR diff.
    """
    component_type = detect_component_type(components)
    if policy_file:
        target_file = _validate_repo_relative_path(policy_file, "policy-file argument")
    else:
        target_file = get_target_file(component_type, environment, is_self_service)

    yaml_block = generate_exception_yaml(
        rule=rule,
        components=components,
        effective_until=effective_until,
        reference_url=reference_url,
        rhoaieng_url=rhoaieng_url,
        rhoai_version=rhoai_version,
        is_self_service=is_self_service,
        is_weekday_restriction=is_weekday_restriction,
        image_ref=image_ref,
        reference_title=reference_title,
        spreadsheet_url=spreadsheet_url,
    )

    if dry_run:
        return {
            "status": "dry_run",
            "target_file": target_file,
            "yaml_block": yaml_block,
            "branch": branch_name,
            "component_type": component_type,
            "mr_url": None,
        }

    WORK_DIR.mkdir(parents=True, exist_ok=True)
    workdir = Path(tempfile.mkdtemp(prefix="conforma-exception-mr-update-", dir=WORK_DIR))
    try:
        clone_dest = str(workdir / "repo")
        repo_url = _get_authenticated_repo_url()
        _run_git(
            [
                "git",
                "clone",
                "--depth=1",
                "--branch",
                DEFAULT_BRANCH,
                "--filter=blob:none",
                "--sparse",
                repo_url,
                clone_dest,
            ],
            timeout=300,
        )
        repo_dir = workdir / "repo"
        policy_dir = str(Path(target_file).parent)
        _run_git(["git", "sparse-checkout", "set", policy_dir], cwd=repo_dir)

        _run_git(["git", "checkout", "-b", branch_name], cwd=repo_dir)

        policy_file = repo_dir / target_file
        if not policy_file.exists():
            return {
                "status": "failed",
                "error": f"Target file not found: {target_file}",
                "target_file": target_file,
                "mr_url": None,
            }

        apply_result = apply_exception_to_policy_file(
            file_path=policy_file,
            yaml_block=yaml_block,
            is_self_service=is_self_service,
            rule=rule,
            components=components,
            effective_until=effective_until,
        )

        action = apply_result["action"]
        if action == "extended":
            commit_msg = _build_commit_message_extend(
                rule=rule,
                components=components,
                rhoai_version=rhoai_version,
                effective_until=effective_until,
                rhoaieng_url=rhoaieng_url,
                reference_url=reference_url,
                spreadsheet_url=spreadsheet_url,
                target_file=target_file,
                exception_risk=exception_risk,
                exception_remediation=exception_remediation,
            )
        else:
            commit_msg = _build_commit_message(
                rule=rule,
                components=components,
                rhoai_version=rhoai_version,
                effective_until=effective_until,
                rhoaieng_url=rhoaieng_url,
                reference_url=reference_url,
                spreadsheet_url=spreadsheet_url,
                target_file=target_file,
                exception_risk=exception_risk,
                exception_remediation=exception_remediation,
            )

        _run_git(["git", "add", target_file], cwd=repo_dir)
        _run_git(["git", "commit", "-m", commit_msg], cwd=repo_dir)

        push_result = subprocess.run(
            ["git", "push", "--force", "origin", f"HEAD:{branch_name}"],
            capture_output=True,
            text=True,
            timeout=60,
            cwd=repo_dir,
            env=gitlab_ops.git_env(),
        )
        if push_result.returncode != 0:
            return {
                "status": "failed",
                "error": f"Force push failed: {push_result.stderr.strip()}",
                "target_file": target_file,
                "branch": branch_name,
                "mr_url": None,
            }

        mr_url = _extract_mr_url(push_result.stdout + push_result.stderr)

        new_title = _build_mr_title(rule, rhoai_version, environment, vendor_tag)
        new_body = _build_mr_body(
            rule=rule,
            components=components,
            rhoai_version=rhoai_version,
            effective_until=effective_until,
            rhoaieng_url=rhoaieng_url,
            reference_url=reference_url,
            spreadsheet_url=spreadsheet_url,
            target_file=target_file,
        )
        sync_result = _sync_mr_description(branch_name, new_title, new_body)
        if sync_result and sync_result.get("mr_url") and not mr_url:
            mr_url = sync_result["mr_url"]

        return {
            "status": "updated",
            "target_file": target_file,
            "branch": branch_name,
            "mr_url": mr_url,
            "yaml_block": yaml_block,
            "component_type": component_type,
            "apply_action": apply_result["action"],
            "apply_detail": apply_result["detail"],
        }
    except subprocess.CalledProcessError as exc:
        return {
            "status": "failed",
            "error": f"Git operation failed: {exc.stderr or exc.stdout}",
            "target_file": target_file,
            "mr_url": None,
        }
    finally:
        import shutil

        shutil.rmtree(workdir, ignore_errors=True)


def _sync_mr_description(
    branch_name: str,
    title: str,
    body: str,
) -> dict | None:
    """Find the open MR for branch_name and update its title + description.

    Returns the update result dict, or None if no open MR was found.
    """
    mrs = gitlab_ops.find_mr(GITLAB_PROJECT, source_branch=branch_name, state="opened")
    if not mrs or mrs[0].get("error"):
        return None
    mr_iid = mrs[0]["mr_iid"]
    return gitlab_ops.update_mr(GITLAB_PROJECT, mr_iid, title=title, description=body)


def update_consolidated_mr(
    branch_name: str,
    rule: str,
    version_specs: list[dict],
    reference_url: str,
    rhoaieng_url: str | None,
    environment: str,
    is_self_service: bool,
    reference_title: str | None = None,
    spreadsheet_url: str | None = None,
    vendor_tag: str | None = None,
    exception_risk: str | None = None,
    exception_remediation: str | None = None,
    policy_file: str | None = None,
    dry_run: bool = False,
) -> dict:
    """Update an existing consolidated MR branch from current main.

    Same pattern as update_mr() but for multi-version exception Merge Requests.
    After force-pushing, syncs the MR title and description to reflect
    the current version_specs.
    """
    if not version_specs:
        return {"status": "failed", "error": "No version_specs provided", "mr_url": None}

    all_components = []
    for spec in version_specs:
        all_components.extend(spec["components"])
    component_type = detect_component_type(all_components)
    if policy_file:
        target_file = _validate_repo_relative_path(policy_file, "policy-file argument")
    else:
        target_file = get_target_file(component_type, environment, is_self_service)

    if dry_run:
        yaml_blocks = []
        for spec in version_specs:
            block = generate_exception_yaml(
                rule=rule,
                components=spec["components"],
                effective_until=spec["effective_until"],
                reference_url=reference_url,
                rhoaieng_url=rhoaieng_url,
                rhoai_version=spec["version"],
                is_self_service=is_self_service,
                reference_title=reference_title,
                spreadsheet_url=spreadsheet_url,
            )
            yaml_blocks.append({"version": spec["version"], "yaml": block})
        return {
            "status": "dry_run",
            "target_file": target_file,
            "yaml_blocks": yaml_blocks,
            "branch": branch_name,
            "component_type": component_type,
            "versions": [s["version"] for s in version_specs],
            "mr_url": None,
        }

    WORK_DIR.mkdir(parents=True, exist_ok=True)
    workdir = Path(tempfile.mkdtemp(prefix="conforma-exception-mr-update-consolidated-", dir=WORK_DIR))
    try:
        clone_dest = str(workdir / "repo")
        repo_url = _get_authenticated_repo_url()
        _run_git(
            [
                "git",
                "clone",
                "--depth=1",
                "--branch",
                DEFAULT_BRANCH,
                "--filter=blob:none",
                "--sparse",
                repo_url,
                clone_dest,
            ],
            timeout=300,
        )
        repo_dir = workdir / "repo"
        policy_dir = str(Path(target_file).parent)
        _run_git(["git", "sparse-checkout", "set", policy_dir], cwd=repo_dir)

        _run_git(["git", "checkout", "-b", branch_name], cwd=repo_dir)

        pf = repo_dir / target_file
        if not pf.exists():
            return {
                "status": "failed",
                "error": f"Target file not found: {target_file}",
                "target_file": target_file,
                "mr_url": None,
            }

        apply_results = []
        for spec in version_specs:
            yaml_block = generate_exception_yaml(
                rule=rule,
                components=spec["components"],
                effective_until=spec["effective_until"],
                reference_url=reference_url,
                rhoaieng_url=rhoaieng_url,
                rhoai_version=spec["version"],
                is_self_service=is_self_service,
                reference_title=reference_title,
                spreadsheet_url=spreadsheet_url,
            )
            result = apply_exception_to_policy_file(
                file_path=pf,
                yaml_block=yaml_block,
                is_self_service=is_self_service,
                rule=rule,
                components=spec["components"],
                effective_until=spec["effective_until"],
            )
            apply_results.append(
                {
                    "version": spec["version"],
                    "action": result["action"],
                    "detail": result["detail"],
                }
            )

        commit_msg = _build_commit_message_consolidated(
            rule=rule,
            version_specs=version_specs,
            rhoaieng_url=rhoaieng_url,
            reference_url=reference_url,
            spreadsheet_url=spreadsheet_url,
            target_file=target_file,
            exception_risk=exception_risk,
            exception_remediation=exception_remediation,
        )

        _run_git(["git", "add", target_file], cwd=repo_dir)
        _run_git(["git", "commit", "-m", commit_msg], cwd=repo_dir)

        push_result = subprocess.run(
            ["git", "push", "--force", "origin", f"HEAD:{branch_name}"],
            capture_output=True,
            text=True,
            timeout=60,
            cwd=repo_dir,
            env=gitlab_ops.git_env(),
        )
        if push_result.returncode != 0:
            return {
                "status": "failed",
                "error": f"Force push failed: {push_result.stderr.strip()}",
                "target_file": target_file,
                "branch": branch_name,
                "mr_url": None,
            }

        mr_url = _extract_mr_url(push_result.stdout + push_result.stderr)

        new_title = _build_mr_title_consolidated(rule, version_specs, environment, vendor_tag)
        new_body = _build_mr_body_consolidated(
            rule=rule,
            version_specs=version_specs,
            rhoaieng_url=rhoaieng_url,
            reference_url=reference_url,
            spreadsheet_url=spreadsheet_url,
            target_file=target_file,
        )
        sync_result = _sync_mr_description(branch_name, new_title, new_body)
        if sync_result and sync_result.get("mr_url") and not mr_url:
            mr_url = sync_result["mr_url"]

        return {
            "status": "updated",
            "target_file": target_file,
            "branch": branch_name,
            "mr_url": mr_url,
            "component_type": component_type,
            "versions": [s["version"] for s in version_specs],
            "apply_results": apply_results,
        }
    except subprocess.CalledProcessError as exc:
        return {
            "status": "failed",
            "error": f"Git operation failed: {exc.stderr or exc.stdout}",
            "target_file": target_file,
            "mr_url": None,
        }
    finally:
        import shutil

        shutil.rmtree(workdir, ignore_errors=True)


def create_consolidated_mr(
    rule: str,
    version_specs: list[dict],
    reference_url: str,
    rhoaieng_url: str | None,
    environment: str,
    is_self_service: bool,
    reference_title: str | None = None,
    spreadsheet_url: str | None = None,
    vendor_tag: str | None = None,
    exception_risk: str | None = None,
    exception_remediation: str | None = None,
    policy_file: str | None = None,
    dry_run: bool = False,
) -> dict:
    """Create a single consolidated MR covering all RHOAI versions for one rule.

    version_specs is a list of dicts:
        [{"version": "rhoai-3.3", "components": [...], "effective_until": "..."}, ...]

    All version blocks are appended to the same policy file in a single commit.
    """
    if not version_specs:
        return {"status": "failed", "error": "No version_specs provided", "mr_url": None}

    all_components = []
    for spec in version_specs:
        all_components.extend(spec["components"])
    component_type = detect_component_type(all_components)
    if policy_file:
        target_file = _validate_repo_relative_path(policy_file, "policy-file argument")
    else:
        target_file = get_target_file(component_type, environment, is_self_service)

    if dry_run:
        yaml_blocks = []
        for spec in version_specs:
            block = generate_exception_yaml(
                rule=rule,
                components=spec["components"],
                effective_until=spec["effective_until"],
                reference_url=reference_url,
                rhoaieng_url=rhoaieng_url,
                rhoai_version=spec["version"],
                is_self_service=is_self_service,
                reference_title=reference_title,
                spreadsheet_url=spreadsheet_url,
            )
            yaml_blocks.append({"version": spec["version"], "yaml": block})
        return {
            "status": "dry_run",
            "target_file": target_file,
            "yaml_blocks": yaml_blocks,
            "component_type": component_type,
            "versions": [s["version"] for s in version_specs],
            "mr_url": None,
        }

    WORK_DIR.mkdir(parents=True, exist_ok=True)
    workdir = Path(tempfile.mkdtemp(prefix="conforma-exception-mr-consolidated-", dir=WORK_DIR))
    try:
        clone_dest = str(workdir / "repo")
        repo_url = _get_authenticated_repo_url()
        _run_git(
            [
                "git",
                "clone",
                "--depth=1",
                "--branch",
                DEFAULT_BRANCH,
                "--filter=blob:none",
                "--sparse",
                repo_url,
                clone_dest,
            ],
            timeout=300,
        )
        repo_dir = workdir / "repo"
        policy_dir = str(Path(target_file).parent)
        _run_git(["git", "sparse-checkout", "set", policy_dir], cwd=repo_dir)

        branch_name = _make_branch_name_consolidated(rule, version_specs)
        _run_git(["git", "checkout", "-b", branch_name], cwd=repo_dir)

        policy_file = repo_dir / target_file
        if not policy_file.exists():
            return {
                "status": "failed",
                "error": f"Target file not found: {target_file}",
                "target_file": target_file,
                "mr_url": None,
            }

        apply_results = []
        for spec in version_specs:
            yaml_block = generate_exception_yaml(
                rule=rule,
                components=spec["components"],
                effective_until=spec["effective_until"],
                reference_url=reference_url,
                rhoaieng_url=rhoaieng_url,
                rhoai_version=spec["version"],
                is_self_service=is_self_service,
                reference_title=reference_title,
                spreadsheet_url=spreadsheet_url,
            )
            result = apply_exception_to_policy_file(
                file_path=policy_file,
                yaml_block=yaml_block,
                is_self_service=is_self_service,
                rule=rule,
                components=spec["components"],
                effective_until=spec["effective_until"],
            )
            apply_results.append(
                {
                    "version": spec["version"],
                    "action": result["action"],
                    "detail": result["detail"],
                }
            )

        commit_msg = _build_commit_message_consolidated(
            rule=rule,
            version_specs=version_specs,
            rhoaieng_url=rhoaieng_url,
            reference_url=reference_url,
            spreadsheet_url=spreadsheet_url,
            target_file=target_file,
            exception_risk=exception_risk,
            exception_remediation=exception_remediation,
        )

        _run_git(["git", "add", target_file], cwd=repo_dir)
        _run_git(["git", "commit", "-m", commit_msg], cwd=repo_dir)

        push_result = subprocess.run(
            ["git", "push", "-u", "origin", branch_name],
            capture_output=True,
            text=True,
            timeout=60,
            cwd=repo_dir,
            env=gitlab_ops.git_env(),
        )

        use_fork = False
        if push_result.returncode != 0:
            fork_url = _ensure_fork(repo_dir)
            if not fork_url:
                return {
                    "status": "failed",
                    "error": f"Push failed and fork creation failed: {push_result.stderr.strip()}",
                    "target_file": target_file,
                    "branch": branch_name,
                    "mr_url": None,
                }
            _run_git(["git", "remote", "add", "fork", fork_url], cwd=repo_dir)
            _run_git(["git", "push", "-u", "fork", branch_name], cwd=repo_dir)
            use_fork = True

        mr_title = _build_mr_title_consolidated(rule, version_specs, environment, vendor_tag)
        mr_body = _build_mr_body_consolidated(
            rule=rule,
            version_specs=version_specs,
            rhoaieng_url=rhoaieng_url,
            reference_url=reference_url,
            spreadsheet_url=spreadsheet_url,
            target_file=target_file,
        )
        mr_create_args = [
            "mr",
            "create",
            "--title",
            mr_title,
            "--description",
            mr_body,
            "--target-branch",
            DEFAULT_BRANCH,
            "--remove-source-branch",
            "-R",
            f"{GITLAB_HOST}/{GITLAB_PROJECT}",
        ]
        if use_fork:
            mr_create_args.extend(["--head", branch_name])

        mr_result = subprocess.run(
            ["glab", *mr_create_args],
            capture_output=True,
            text=True,
            timeout=30,
            cwd=repo_dir,
        )

        if mr_result.returncode != 0:
            return {
                "status": "failed",
                "error": mr_result.stderr.strip() or mr_result.stdout.strip(),
                "target_file": target_file,
                "branch": branch_name,
                "mr_url": None,
                "use_fork": use_fork,
            }

        mr_url = _extract_mr_url(mr_result.stdout + mr_result.stderr)
        return {
            "status": "created",
            "target_file": target_file,
            "branch": branch_name,
            "mr_url": mr_url,
            "component_type": component_type,
            "use_fork": use_fork,
            "versions": [s["version"] for s in version_specs],
            "apply_results": apply_results,
        }
    except subprocess.CalledProcessError as exc:
        return {
            "status": "failed",
            "error": f"Git operation failed: {exc.stderr or exc.stdout}",
            "target_file": target_file,
            "mr_url": None,
        }
    finally:
        import shutil

        shutil.rmtree(workdir, ignore_errors=True)


def _make_branch_name_consolidated(rule: str, version_specs: list[dict]) -> str:
    """Generate a branch name for a consolidated MR (no version suffix)."""
    rule_short = rule.replace(".", "-").replace(":", "-")[:30]
    comp_short = version_specs[0]["components"][0][:20] if version_specs[0]["components"] else "unknown"
    return f"conforma-exception/{rule_short}/{comp_short}"


def _ensure_fork(repo_dir: Path) -> str | None:
    """Create or get existing fork of the upstream project, return authenticated URL."""
    result = subprocess.run(
        [
            "glab",
            "repo",
            "fork",
            GITLAB_PROJECT,
            "--hostname",
            GITLAB_HOST,
            "--clone=false",
        ],
        capture_output=True,
        text=True,
        timeout=30,
        cwd=repo_dir,
    )
    output = result.stdout + result.stderr
    fork_project = _extract_fork_project(output)
    if fork_project:
        return _get_authenticated_repo_url(fork_project)
    if "already exists" in output.lower():
        user_result = subprocess.run(
            ["glab", "auth", "status", "--hostname", GITLAB_HOST],
            capture_output=True,
            text=True,
            timeout=10,
        )
        user_match = re.search(r"Logged in .* as (\S+)", user_result.stdout + user_result.stderr)
        if user_match:
            username = user_match.group(1)
            project_name = GITLAB_PROJECT.split("/")[-1]
            return _get_authenticated_repo_url(f"{username}/{project_name}")
    return None


def _extract_fork_project(output: str) -> str | None:
    """Extract fork project path from glab fork output."""
    match = re.search(rf"{re.escape(GITLAB_HOST)}/([^\s]+?)(?:\.git)?(?:\s|$)", output)
    if match:
        return match.group(1)
    return None


def _make_branch_name(rule: str, version: str, components: list[str]) -> str:
    """Generate a descriptive branch name."""
    rule_short = rule.replace(".", "-").replace(":", "-")[:30]
    comp_short = components[0][:20] if components else "unknown"
    version_short = version.replace("rhoai-", "")
    return f"conforma-exception/{rule_short}/{comp_short}-{version_short}"


def _run_git(cmd: list[str], cwd: Path | None = None, timeout: int = 60) -> subprocess.CompletedProcess:
    """Run a git command, raising on failure.

    Uses gitlab_ops.run_git() to respect GITLAB_SSL_VERIFY settings.
    Injects Bearer token via http.extraheader for authenticated operations
    (clone, push, fetch) so tokens are never embedded in URLs.
    """
    token = _get_gitlab_token()
    needs_auth = any(sub in cmd for sub in ("clone", "push", "fetch", "pull"))
    if token and needs_auth:
        git_idx = cmd.index("git") if "git" in cmd else 0
        cmd = [
            *cmd[: git_idx + 1],
            "-c", f"http.extraheader=Authorization: Bearer {token}",
            *cmd[git_idx + 1 :],
        ]
    return gitlab_ops.run_git(cmd, cwd=cwd, timeout=timeout, check=True)


def _extract_mr_url(output: str) -> str | None:
    """Extract MR URL from glab output."""
    match = re.search(r"(https://[^\s]+merge_requests/\d+)", output)
    return match.group(1) if match else None


def remove_expired_mr(
    rule: str,
    effective_until: str,
    rhoai_version: str,
    environment: str,
    components: list[str] | None = None,
    reference_url: str | None = None,
    clone_dir: str | None = None,
    policy_file: str | None = None,
    dry_run: bool = False,
) -> dict:
    """Create a GitLab MR that removes an expired exception from a policy file."""
    if policy_file:
        target_file = _validate_repo_relative_path(policy_file, "policy-file argument")
    else:
        comp_type = detect_component_type(components or [])
        target_file = get_target_file(comp_type, environment, is_self_service=False)

    WORK_DIR.mkdir(parents=True, exist_ok=True)

    if clone_dir:
        repo_dir = Path(clone_dir)
        is_temp = False
    else:
        import tempfile

        workdir = Path(tempfile.mkdtemp(prefix="conforma-exception-remove-", dir=WORK_DIR))
        repo_url = _get_authenticated_repo_url()
        repo_dir = workdir / "repo"
        try:
            _run_git(
                ["git", "clone", "--depth=1", "--branch", DEFAULT_BRANCH, repo_url, str(repo_dir)],
                timeout=300,
            )
        except subprocess.CalledProcessError as exc:
            return {
                "status": "failed",
                "error": f"Clone failed: {exc.stderr or exc.stdout}",
                "mr_url": None,
            }
        is_temp = True

    try:
        file_path = repo_dir / target_file
        if not file_path.exists():
            return {
                "status": "failed",
                "error": f"Policy file not found: {target_file}",
                "mr_url": None,
            }

        result = remove_exception_from_policy_file(
            file_path,
            rule,
            effective_until,
            components,
        )

        if result["action"] == "not_found":
            return {
                "status": "not_found",
                "detail": result["detail"],
                "mr_url": None,
            }

        if dry_run:
            return {
                "status": "dry_run",
                "target_file": target_file,
                "remove_result": result,
                "mr_url": None,
            }

        rule_short = rule.replace(".", "-").replace(":", "-")[:30]
        version_short = rhoai_version.replace("rhoai-", "")
        branch_name = f"conforma-remove-expired/{rule_short}-{version_short}"

        _run_git(["git", "checkout", "-b", branch_name], cwd=repo_dir)
        _run_git(["git", "add", target_file], cwd=repo_dir)

        commit_msg = _build_commit_message_remove(
            rule=rule,
            rhoai_version=rhoai_version,
            effective_until=effective_until,
            components=components,
            reference_url=reference_url,
            target_file=target_file,
        )
        _run_git(["git", "commit", "-m", commit_msg], cwd=repo_dir)

        push_result = subprocess.run(
            ["git", "push", "-u", "origin", branch_name],
            capture_output=True,
            text=True,
            timeout=60,
            cwd=repo_dir,
            env=gitlab_ops.git_env(),
        )

        use_fork = False
        if push_result.returncode != 0:
            fork_url = _ensure_fork(repo_dir)
            if not fork_url:
                return {
                    "status": "failed",
                    "error": f"Push failed and fork creation failed: {push_result.stderr.strip()}",
                    "mr_url": None,
                }
            _run_git(["git", "remote", "add", "fork", fork_url], cwd=repo_dir)
            _run_git(["git", "push", "-u", "fork", branch_name], cwd=repo_dir)
            use_fork = True

        mr_title = f"Remove expired conforma exception: {rule} ({rhoai_version})"
        mr_body_lines = [
            f"## Remove expired exception: `{rule}`",
            "",
            "| Field | Value |",
            "|-------|-------|",
            f"| **Rule** | `{rule}` |",
            f"| **RHOAI version** | `{rhoai_version}` |",
            f"| **Expired effectiveUntil** | `{effective_until}` |",
            f"| **Components** | `{', '.join(components) if components else '(unscoped, all)'}` |",
            f"| **Policy file** | `{target_file}` |",
        ]
        if reference_url:
            mr_body_lines.append(f"| **Reference** | {reference_url} |")
        mr_body_lines.extend(
            [
                "",
                "---",
                f"*Generated by `{PROVENANCE_SKILL}`*",
            ]
        )
        mr_body = "\n".join(mr_body_lines)

        mr_create_args = [
            "mr",
            "create",
            "--title",
            mr_title,
            "--description",
            mr_body,
            "--target-branch",
            DEFAULT_BRANCH,
            "--remove-source-branch",
            "-R",
            f"{GITLAB_HOST}/{GITLAB_PROJECT}",
        ]
        if use_fork:
            mr_create_args.extend(["--head", branch_name])

        mr_result = subprocess.run(
            ["glab", *mr_create_args],
            capture_output=True,
            text=True,
            timeout=30,
            cwd=repo_dir,
        )

        if mr_result.returncode != 0:
            return {
                "status": "failed",
                "error": mr_result.stderr.strip() or mr_result.stdout.strip(),
                "mr_url": None,
            }

        mr_url = _extract_mr_url(mr_result.stdout + mr_result.stderr)
        return {
            "status": "created",
            "target_file": target_file,
            "branch": branch_name,
            "mr_url": mr_url,
            "remove_result": result,
            "use_fork": use_fork,
        }
    except subprocess.CalledProcessError as exc:
        return {
            "status": "failed",
            "error": f"Git operation failed: {exc.stderr or exc.stdout}",
            "mr_url": None,
        }
    finally:
        if is_temp:
            import shutil

            shutil.rmtree(workdir, ignore_errors=True)


def modernize_exception_mr(
    rule: str,
    old_effective_until: str,
    version_specs: list[dict],
    environment: str,
    reference_url: str | None = None,
    rhoaieng_url: str | None = None,
    old_components: list[str] | None = None,
    policy_file: str | None = None,
    spreadsheet_url: str | None = None,
    vendor_tag: str | None = None,
    exception_risk: str | None = None,
    exception_remediation: str | None = None,
    dry_run: bool = False,
) -> dict:
    """Create a single MR that removes an unscoped block (no componentNames) and adds new scoped entries.

    Combines remove_exception_from_policy_file() + generate_exception_yaml() in
    one branch/commit so the modernization is atomic.

    version_specs: [{"version": "rhoai-3.3", "components": [...], "effective_until": "..."}, ...]
    """
    if not version_specs:
        return {"status": "failed", "error": "No version_specs provided", "mr_url": None}

    all_components = []
    for spec in version_specs:
        all_components.extend(spec["components"])

    if policy_file:
        target_file = _validate_repo_relative_path(policy_file, "policy-file argument")
    else:
        comp_type = detect_component_type(all_components or old_components or [])
        target_file = get_target_file(comp_type, environment, is_self_service=False)

    WORK_DIR.mkdir(parents=True, exist_ok=True)
    workdir = Path(tempfile.mkdtemp(prefix="conforma-exception-modernize-", dir=WORK_DIR))
    try:
        repo_url = _get_authenticated_repo_url()
        repo_dir = workdir / "repo"
        _run_git(
            ["git", "clone", "--depth=1", "--branch", DEFAULT_BRANCH, repo_url, str(repo_dir)],
            timeout=300,
        )

        pf = repo_dir / target_file
        if not pf.exists():
            return {
                "status": "failed",
                "error": f"Policy file not found: {target_file}",
                "mr_url": None,
            }

        remove_result = remove_exception_from_policy_file(
            pf,
            rule,
            old_effective_until,
            old_components,
        )

        if remove_result["action"] == "not_found":
            return {
                "status": "failed",
                "error": f"Could not find unscoped block to remove: {remove_result['detail']}",
                "mr_url": None,
            }

        apply_results = []
        for spec in version_specs:
            yaml_block = generate_exception_yaml(
                rule=rule,
                components=spec["components"],
                effective_until=spec["effective_until"],
                reference_url=reference_url or "",
                rhoaieng_url=rhoaieng_url,
                rhoai_version=spec["version"],
                is_self_service=False,
                spreadsheet_url=spreadsheet_url,
            )
            result = apply_exception_to_policy_file(
                file_path=pf,
                yaml_block=yaml_block,
                is_self_service=False,
                rule=rule,
                components=spec["components"],
                effective_until=spec["effective_until"],
            )
            apply_results.append(
                {
                    "version": spec["version"],
                    "action": result["action"],
                    "detail": result["detail"],
                }
            )

        versions = [s["version"] for s in version_specs]
        subject = f"Modernize conforma exception: {rule} ({', '.join(versions)})"
        lines = [
            subject,
            "",
            "Replaced unscoped exception (no componentNames) with properly-scoped entries.",
            f"  Rule: {rule}",
            f"  Removed old effectiveUntil: {old_effective_until}",
            f"  Policy file: {target_file}",
        ]
        if exception_risk:
            lines.append(f"  Risk: {exception_risk}")
        if exception_remediation:
            lines.append(f"  Remediation: {exception_remediation}")
        lines.append("")

        for spec in version_specs:
            lines.append(f"  {spec['version']}:")
            lines.append(f"    Components: {', '.join(spec['components'])}")
            lines.append(f"    Effective until: {spec['effective_until']}")
            lines.append("")

        if rhoaieng_url:
            lines.append(f"RHOAIENG: {rhoaieng_url}")
        if reference_url:
            lines.append(f"Reference: {reference_url}")
        if spreadsheet_url:
            lines.append(f"Spreadsheet: {spreadsheet_url}")
        if rhoaieng_url or reference_url or spreadsheet_url:
            lines.append("")

        lines.extend(
            [
                "---",
                f"Generated by: {PROVENANCE_SKILL}",
                f"Source: https://github.com/{PROVENANCE_REPO}",
                f"User: {getpass.getuser()}@{platform.node()}",
            ]
        )
        commit_msg = "\n".join(lines)

        rule_short = rule.replace(".", "-").replace(":", "-")[:30]
        comp_short = version_specs[0]["components"][0][:20] if version_specs[0]["components"] else "unknown"
        branch_name = f"conforma-modernize/{rule_short}/{comp_short}"

        if dry_run:
            return {
                "status": "dry_run",
                "target_file": target_file,
                "remove_result": remove_result,
                "apply_results": apply_results,
                "versions": versions,
                "branch_name": branch_name,
                "mr_url": None,
            }

        _run_git(["git", "checkout", "-b", branch_name], cwd=repo_dir)
        _run_git(["git", "add", target_file], cwd=repo_dir)
        _run_git(["git", "commit", "-m", commit_msg], cwd=repo_dir)

        push_result = subprocess.run(
            ["git", "push", "-u", "origin", branch_name],
            capture_output=True,
            text=True,
            timeout=60,
            cwd=repo_dir,
            env=gitlab_ops.git_env(),
        )

        use_fork = False
        if push_result.returncode != 0:
            fork_url = _ensure_fork(repo_dir)
            if not fork_url:
                return {
                    "status": "failed",
                    "error": f"Push failed and fork creation failed: {push_result.stderr.strip()}",
                    "mr_url": None,
                }
            _run_git(["git", "remote", "add", "fork", fork_url], cwd=repo_dir)
            _run_git(["git", "push", "-u", "fork", branch_name], cwd=repo_dir)
            use_fork = True

        mr_title = f"[RHOAI] Modernize conforma exception: {rule}"
        if vendor_tag:
            mr_title = f"[{vendor_tag}] {mr_title}"

        mr_body_lines = [
            f"## Modernize exception: `{rule}`",
            "",
            "Replaced unscoped exception (no `componentNames`) with properly-scoped entries.",
            "",
            "| Field | Value |",
            "|-------|-------|",
            f"| **Rule** | `{rule}` |",
            f"| **Old effectiveUntil** | `{old_effective_until}` |",
            f"| **Versions** | {', '.join(f'`{v}`' for v in versions)} |",
            f"| **Policy file** | `{target_file}` |",
            "",
        ]

        for spec in version_specs:
            mr_body_lines.append(f"### `{spec['version']}`")
            mr_body_lines.append("")
            mr_body_lines.append(f"**Effective until**: `{spec['effective_until']}`")
            mr_body_lines.append("")
            mr_body_lines.append("**Components**:")
            for comp in spec["components"]:
                mr_body_lines.append(f"- `{comp}`")
            mr_body_lines.append("")

        if rhoaieng_url or reference_url:
            mr_body_lines.append("### References")
            mr_body_lines.append("")
            if rhoaieng_url:
                mr_body_lines.append(f"- **RHOAIENG**: {rhoaieng_url}")
            if reference_url:
                mr_body_lines.append(f"- **Reference**: {reference_url}")
            mr_body_lines.append("")

        mr_body_lines.extend(
            [
                "---",
                "",
                f"*Generated by `{PROVENANCE_SKILL}` | "
                f"[source](https://github.com/{PROVENANCE_REPO}) | "
                f"`{getpass.getuser()}@{platform.node()}`*",
            ]
        )
        mr_body = "\n".join(mr_body_lines)

        mr_create_args = [
            "mr",
            "create",
            "--title",
            mr_title,
            "--description",
            mr_body,
            "--target-branch",
            DEFAULT_BRANCH,
            "--remove-source-branch",
            "-R",
            f"{GITLAB_HOST}/{GITLAB_PROJECT}",
        ]
        if use_fork:
            mr_create_args.extend(["--head", branch_name])

        mr_result = subprocess.run(
            ["glab", *mr_create_args],
            capture_output=True,
            text=True,
            timeout=30,
            cwd=repo_dir,
        )

        if mr_result.returncode != 0:
            return {
                "status": "failed",
                "error": mr_result.stderr.strip() or mr_result.stdout.strip(),
                "mr_url": None,
            }

        mr_url = _extract_mr_url(mr_result.stdout + mr_result.stderr)
        return {
            "status": "created",
            "target_file": target_file,
            "branch": branch_name,
            "mr_url": mr_url,
            "remove_result": remove_result,
            "apply_results": apply_results,
            "versions": versions,
            "use_fork": use_fork,
        }
    except subprocess.CalledProcessError as exc:
        return {
            "status": "failed",
            "error": f"Git operation failed: {exc.stderr or exc.stdout}",
            "mr_url": None,
        }
    finally:
        import shutil

        shutil.rmtree(workdir, ignore_errors=True)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Create GitLab MR for Conforma exception")
    parser.add_argument("--rule", required=True)
    parser.add_argument("--components", default=None, help="Comma-separated (single-version mode)")
    parser.add_argument("--effective-until", default=None, help="Single-version mode")
    parser.add_argument("--reference-url", default=None, help="PSX/OCPEXCEPT ticket URL")
    parser.add_argument("--reference-title", default=None, help="PSX/OCPEXCEPT ticket title")
    parser.add_argument("--rhoaieng-url", default=None)
    parser.add_argument("--remediation-plan-url", default=None)
    parser.add_argument("--rhoai-version", default=None, help="Single-version mode")
    parser.add_argument("--environment", required=True, choices=["prod", "stage"])
    parser.add_argument("--spreadsheet-url", default=None, help="Tracking spreadsheet URL (YAML comment)")
    parser.add_argument(
        "--self-service",
        action="store_true",
        help="Target exceptions/ dir (set automatically by orchestrator from workflow)",
    )
    parser.add_argument("--image-ref", default=None, help="SHA digest for weekday_restriction")
    parser.add_argument(
        "--vendor-tag",
        default=None,
        help="Vendor/distinguisher tag prepended to MR title (e.g. AMD, Intel)",
    )
    parser.add_argument("--update-mr", default=None, help="Existing MR branch to update")
    parser.add_argument(
        "--version-specs-json",
        default=None,
        help=(
            "JSON array of version specs for consolidated mode. Each entry: "
            '{"version": "rhoai-X.Y", "components": [...], "effective_until": "..."}. '
            "When provided, --components/--effective-until/--rhoai-version are ignored."
        ),
    )
    parser.add_argument("--template", default=None, help="Template category ID from exception_templates.yaml")
    parser.add_argument(
        "--justification", default=None, help="Justification template ID (e.g., dev_preview, code_frozen)"
    )
    parser.add_argument("--exception-risk", default=None, help="Exception risk text (overrides template)")
    parser.add_argument("--exception-remediation", default=None, help="Exception remediation text (overrides template)")
    parser.add_argument(
        "--remove-expired-exception",
        action="store_true",
        help="Remove an expired exception instead of adding/extending one",
    )
    parser.add_argument(
        "--modernize-expired-exception",
        action="store_true",
        help="Remove unscoped block (no componentNames) and add new scoped entries in one MR. "
        "Requires --version-specs-json for the new entries.",
    )
    parser.add_argument("--clone-dir", default=None, help="Existing repo clone to use (remove-expired-exception mode)")
    parser.add_argument(
        "--policy-file",
        default=None,
        help="Override auto-detected policy file path within the repo "
        "(e.g. config/.../fbc-rhoai-prod.yaml). Required for unscoped "
        "FBC exceptions where component names are absent.",
    )
    parser.add_argument("--dry-run", action="store_true")
    return parser.parse_args()


def main() -> int:
    args = parse_args()

    if args.remove_expired_exception:
        if not args.rule or not args.effective_until or not args.rhoai_version:
            print(
                "Error: --rule, --effective-until, and --rhoai-version are required "
                "for --remove-expired-exception mode.",
                file=sys.stderr,
            )
            return 1
        components = [c.strip() for c in args.components.split(",")] if args.components else None
        result = remove_expired_mr(
            rule=args.rule,
            effective_until=args.effective_until,
            rhoai_version=args.rhoai_version,
            environment=args.environment,
            components=components,
            reference_url=args.reference_url,
            clone_dir=args.clone_dir,
            policy_file=args.policy_file,
            dry_run=args.dry_run,
        )
        print(json.dumps(result, indent=2))
        return 0 if result["status"] in ("created", "dry_run", "not_found") else 1

    if args.modernize_expired_exception:
        if not args.rule or not args.effective_until:
            print(
                "Error: --rule and --effective-until are required for --modernize-expired-exception mode.",
                file=sys.stderr,
            )
            return 1
        if not args.version_specs_json:
            print(
                "Error: --version-specs-json is required for --modernize-expired-exception "
                "(defines the new scoped entries to create).",
                file=sys.stderr,
            )
            return 1
        old_components = [c.strip() for c in args.components.split(",")] if args.components else None
        version_specs = json.loads(args.version_specs_json)
        result = modernize_exception_mr(
            rule=args.rule,
            old_effective_until=args.effective_until,
            version_specs=version_specs,
            environment=args.environment,
            reference_url=args.reference_url,
            rhoaieng_url=args.rhoaieng_url,
            old_components=old_components,
            policy_file=args.policy_file,
            spreadsheet_url=args.spreadsheet_url,
            vendor_tag=args.vendor_tag,
            exception_risk=args.exception_risk,
            exception_remediation=args.exception_remediation,
            dry_run=args.dry_run,
        )
        print(json.dumps(result, indent=2))
        return 0 if result["status"] in ("created", "dry_run") else 1

    if not args.reference_url:
        print(
            "Error: --reference-url is required for add/extend modes.",
            file=sys.stderr,
        )
        return 1

    # --- Resolve template + justification if provided ---
    if args.template:
        from create_jira_ticket import resolve_template

        versions_str = args.rhoai_version or ""
        versions_list = [v.strip() for v in versions_str.split(",") if v.strip()]
        rule_key = args.rule.split(":", 1)[1] if ":" in args.rule else args.rule
        components_str = args.components or ""
        components_list = [c.strip() for c in components_str.split(",") if c.strip()]
        template_vars = {
            "rule": args.rule,
            "rule_key": rule_key,
            "components": ", ".join(components_list),
            "component_count": str(len(components_list)),
            "versions": ", ".join(versions_list) if versions_list else versions_str,
            "version_count": str(len(versions_list)) if versions_list else "1",
            "vendor": args.vendor_tag or "",
            "rhoaieng_exception_approval_url": args.rhoaieng_url or args.reference_url or "",
            "rhoaieng_jira_violation_url": args.remediation_plan_url or args.rhoaieng_url or "",
            "remediation_plan_url": args.remediation_plan_url or "",
            "effective_until": args.effective_until or "",
        }
        resolved = resolve_template(
            args.template,
            template_vars,
            justification_id=args.justification,
        )
        if not args.exception_risk:
            args.exception_risk = resolved.get("risk")
        if not args.exception_remediation:
            args.exception_remediation = resolved.get("remediation")

    # Consolidated mode: single MR for all versions
    if args.version_specs_json:
        version_specs = json.loads(args.version_specs_json)
        if args.update_mr:
            result = update_consolidated_mr(
                branch_name=args.update_mr,
                rule=args.rule,
                version_specs=version_specs,
                reference_url=args.reference_url,
                rhoaieng_url=args.rhoaieng_url,
                environment=args.environment,
                is_self_service=args.self_service,
                reference_title=args.reference_title,
                spreadsheet_url=args.spreadsheet_url,
                vendor_tag=args.vendor_tag,
                exception_risk=args.exception_risk,
                exception_remediation=args.exception_remediation,
                policy_file=args.policy_file,
                dry_run=args.dry_run,
            )
        else:
            result = create_consolidated_mr(
                rule=args.rule,
                version_specs=version_specs,
                reference_url=args.reference_url,
                rhoaieng_url=args.rhoaieng_url,
                environment=args.environment,
                is_self_service=args.self_service,
                reference_title=args.reference_title,
                spreadsheet_url=args.spreadsheet_url,
                vendor_tag=args.vendor_tag,
                exception_risk=args.exception_risk,
                exception_remediation=args.exception_remediation,
                policy_file=args.policy_file,
                dry_run=args.dry_run,
            )
        print(json.dumps(result, indent=2))
        return 0 if result["status"] in ("created", "updated", "dry_run") else 1

    # Single-version mode (backward compatible)
    if not args.components or not args.effective_until or not args.rhoai_version:
        print(
            "Error: --components, --effective-until, and --rhoai-version are required "
            "in single-version mode (when --version-specs-json is not provided).",
            file=sys.stderr,
        )
        return 1

    components = [c.strip() for c in args.components.split(",")]
    is_weekday = args.rule == "schedule.weekday_restriction"

    if args.update_mr:
        result = update_mr(
            branch_name=args.update_mr,
            rule=args.rule,
            components=components,
            effective_until=args.effective_until,
            reference_url=args.reference_url,
            rhoaieng_url=args.rhoaieng_url,
            rhoai_version=args.rhoai_version,
            environment=args.environment,
            is_self_service=args.self_service,
            is_weekday_restriction=is_weekday,
            image_ref=args.image_ref,
            reference_title=args.reference_title,
            spreadsheet_url=args.spreadsheet_url,
            vendor_tag=args.vendor_tag,
            exception_risk=args.exception_risk,
            exception_remediation=args.exception_remediation,
            policy_file=args.policy_file,
            dry_run=args.dry_run,
        )
    else:
        result = create_mr(
            rule=args.rule,
            components=components,
            effective_until=args.effective_until,
            reference_url=args.reference_url,
            rhoaieng_url=args.rhoaieng_url,
            rhoai_version=args.rhoai_version,
            environment=args.environment,
            is_self_service=args.self_service,
            is_weekday_restriction=is_weekday,
            image_ref=args.image_ref,
            reference_title=args.reference_title,
            spreadsheet_url=args.spreadsheet_url,
            vendor_tag=args.vendor_tag,
            exception_risk=args.exception_risk,
            exception_remediation=args.exception_remediation,
            policy_file=args.policy_file,
            dry_run=args.dry_run,
        )
    print(json.dumps(result, indent=2))
    return 0 if result["status"] in ("created", "updated", "dry_run") else 1


if __name__ == "__main__":
    sys.exit(main())
