"""Exception Merge Request text generation — commit messages, titles, and bodies."""

from __future__ import annotations

from __future__ import annotations
import argparse
import getpass
import json
import os
import platform
import posixpath
import re
import subprocess
import sys
import tempfile
from pathlib import Path
import gitlab_ops
import konflux_environment


PROVENANCE_REPO = "opendatahub-io/aiops-infra"


PROVENANCE_SKILL = "conforma-exception-ai-skill"


def build_commit_message(
    rule: str,
    components: list[str],
    rhoai_version: str,
    effective_until: str,
    rhoaieng_url: str | None = None,
    reference_url: str | None = None,
    spreadsheet_url: str | None = None,
    target_file: str | None = None,
    exception_risk: str | None = None,
    exception_remediation: str | None = None,
) -> str:
    """Build a structured, multi-line commit message with provenance."""
    subject = f"Add conforma exception: {rule} ({rhoai_version})"

    lines = [
        subject,
        "",
        "Exception details:",
        f"  Rule: {rule}",
        f"  RHOAI version: {rhoai_version}",
        f"  Effective until: {effective_until}",
        f"  Components: {', '.join(components)}",
    ]

    if target_file:
        lines.append(f"  Policy file: {target_file}")

    if exception_risk:
        lines.append(f"  Risk: {exception_risk}")
    if exception_remediation:
        lines.append(f"  Remediation: {exception_remediation}")

    lines.append("")

    if rhoaieng_url:
        lines.append(f"RHOAIENG: {rhoaieng_url}")
    if reference_url:
        lines.append(f"Reference: {reference_url}")
    if spreadsheet_url:
        lines.append(f"Spreadsheet: {spreadsheet_url}")

    if rhoaieng_url or reference_url or spreadsheet_url:
        lines.append("")

    lines.extend(
        [
            "---",
            f"Generated by: {PROVENANCE_SKILL}",
            f"Source: https://github.com/{PROVENANCE_REPO}",
            f"User: {getpass.getuser()}@{platform.node()}",
        ]
    )

    return "\n".join(lines)


def build_mr_body(
    rule: str,
    components: list[str],
    rhoai_version: str,
    effective_until: str,
    rhoaieng_url: str | None = None,
    reference_url: str | None = None,
    spreadsheet_url: str | None = None,
    target_file: str | None = None,
) -> str:
    """Build a markdown-formatted MR description for GitLab rendering."""
    lines = [
        f"## Exception: `{rule}` for `{rhoai_version}`",
        "",
        "| Field | Value |",
        "|-------|-------|",
        f"| **Rule** | `{rule}` |",
        f"| **RHOAI version** | `{rhoai_version}` |",
        f"| **Effective until** | `{effective_until}` |",
        f"| **Policy file** | `{target_file or 'N/A'}` |",
        "",
        "### Components",
        "",
    ]
    for comp in components:
        lines.append(f"- `{comp}`")

    lines.append("")

    if rhoaieng_url or reference_url or spreadsheet_url:
        lines.append("### References")
        lines.append("")
        if rhoaieng_url:
            lines.append(f"- **RHOAIENG**: {rhoaieng_url}")
        if reference_url:
            lines.append(f"- **PSX/Reference**: {reference_url}")
        if spreadsheet_url:
            lines.append(f"- **Spreadsheet**: {spreadsheet_url}")
        lines.append("")

    lines.extend(
        [
            "---",
            "",
            f"*Generated by `{PROVENANCE_SKILL}` | "
            f"[source](https://github.com/{PROVENANCE_REPO}) | "
            f"`{getpass.getuser()}@{platform.node()}`*",
        ]
    )

    return "\n".join(lines)


def build_mr_title(
    rule: str, rhoai_version: str, environment: str, vendor_tag: str | None = None
) -> str:
    """Build the MR title, including vendor tag and environment prefix."""
    env_prefix = f"[{environment}] " if environment else ""
    title = f"{env_prefix}[RHOAI] Conforma exception: {rule} for {rhoai_version}"
    if vendor_tag:
        title = f"[{vendor_tag}] {title}"
    return title


def build_mr_title_consolidated(
    rule: str, version_specs: list[dict], environment: str, vendor_tag: str | None = None
) -> str:
    """Build MR title for a consolidated (multi-version) exception MR."""
    versions = [s["version"] for s in version_specs]
    if len(versions) == 1:
        version_str = versions[0]
    else:
        version_str = f"{versions[0]}..{versions[-1]}"
    env_prefix = f"[{environment}] " if environment else ""
    title = f"{env_prefix}[RHOAI] Conforma exception: {rule} for {version_str}"
    if vendor_tag:
        title = f"[{vendor_tag}] {title}"
    return title


def build_commit_message_consolidated(
    rule: str,
    version_specs: list[dict],
    rhoaieng_url: str | None = None,
    reference_url: str | None = None,
    spreadsheet_url: str | None = None,
    target_file: str | None = None,
    exception_risk: str | None = None,
    exception_remediation: str | None = None,
) -> str:
    """Build commit message for a consolidated MR covering multiple RHOAI versions."""
    versions = [s["version"] for s in version_specs]
    subject = f"Add conforma exception: {rule} ({', '.join(versions)})"

    lines = [
        subject,
        "",
        "Exception details:",
        f"  Rule: {rule}",
    ]
    if target_file:
        lines.append(f"  Policy file: {target_file}")
    if exception_risk:
        lines.append(f"  Risk: {exception_risk}")
    if exception_remediation:
        lines.append(f"  Remediation: {exception_remediation}")
    lines.append("")

    for spec in version_specs:
        lines.append(f"  {spec['version']}:")
        lines.append(f"    Components: {', '.join(spec['components'])}")
        lines.append(f"    Effective until: {spec['effective_until']}")
        lines.append("")

    if rhoaieng_url:
        lines.append(f"RHOAIENG: {rhoaieng_url}")
    if reference_url:
        lines.append(f"Reference: {reference_url}")
    if spreadsheet_url:
        lines.append(f"Spreadsheet: {spreadsheet_url}")

    if rhoaieng_url or reference_url or spreadsheet_url:
        lines.append("")

    lines.extend(
        [
            "---",
            f"Generated by: {PROVENANCE_SKILL}",
            f"Source: https://github.com/{PROVENANCE_REPO}",
            f"User: {getpass.getuser()}@{platform.node()}",
        ]
    )

    return "\n".join(lines)


def build_mr_body_consolidated(
    rule: str,
    version_specs: list[dict],
    rhoaieng_url: str | None = None,
    reference_url: str | None = None,
    spreadsheet_url: str | None = None,
    target_file: str | None = None,
) -> str:
    """Build MR description for a consolidated (multi-version) exception MR."""
    versions = [s["version"] for s in version_specs]
    lines = [
        f"## Exception: `{rule}` for {', '.join(f'`{v}`' for v in versions)}",
        "",
        "| Field | Value |",
        "|-------|-------|",
        f"| **Rule** | `{rule}` |",
        f"| **RHOAI versions** | {', '.join(f'`{v}`' for v in versions)} |",
        f"| **Policy file** | `{target_file or 'N/A'}` |",
        "",
    ]

    for spec in version_specs:
        lines.append(f"### `{spec['version']}`")
        lines.append("")
        lines.append(f"**Effective until**: `{spec['effective_until']}`")
        lines.append("")
        lines.append("**Components**:")
        for comp in spec["components"]:
            lines.append(f"- `{comp}`")
        lines.append("")

    if rhoaieng_url or reference_url or spreadsheet_url:
        lines.append("### References")
        lines.append("")
        if rhoaieng_url:
            lines.append(f"- **RHOAIENG**: {rhoaieng_url}")
        if reference_url:
            lines.append(f"- **PSX/Reference**: {reference_url}")
        if spreadsheet_url:
            lines.append(f"- **Spreadsheet**: {spreadsheet_url}")
        lines.append("")

    lines.extend(
        [
            "---",
            "",
            f"*Generated by `{PROVENANCE_SKILL}` | "
            f"[source](https://github.com/{PROVENANCE_REPO}) | "
            f"`{getpass.getuser()}@{platform.node()}`*",
        ]
    )

    return "\n".join(lines)

