"""Git operations: clone, branch, commit, push, and dry-run diff."""

import logging
import os
import shutil
import subprocess
from datetime import datetime
from pathlib import Path
from typing import List, Optional, Tuple

from constants import AUTO_GENERATED_RHOAI_TENANT, REPO_BRANCH, REPO_URL
from util import GITPYTHON_AVAILABLE, run_git_cmd

if GITPYTHON_AVAILABLE:
    from git import Repo
    from git.exc import GitCommandError

logger = logging.getLogger(__name__)


def _partition_staging_paths(paths: List[str]) -> Tuple[List[str], List[str]]:
    """
    Split paths into config vs auto-generated rhoai-tenant subtree only.
    Only paths under tenants-config/auto-generated/cluster/stone-prod-p02/tenants/rhoai-tenant
    are treated as autogen staging (never the whole auto-generated tree).
    """
    prefix = AUTO_GENERATED_RHOAI_TENANT.rstrip("/")
    config: List[str] = []
    autogen: List[str] = []
    for p in paths:
        pn = p.rstrip("/")
        if pn == prefix or pn.startswith(prefix + "/"):
            autogen.append(p)
        else:
            config.append(p)
    return config, autogen


def clone_repo(
    repo_dir: Path,
    repo_url: str = REPO_URL,
    branch: str = REPO_BRANCH,
) -> Path:
    """
    Clone the repository fresh (removes existing directory if present).
    Returns path to cloned repo.
    """
    logger.info("Removing existing directory if present: %s", repo_dir)
    if repo_dir.exists():
        shutil.rmtree(repo_dir)

    logger.info("Cloning %s (branch: %s) into %s", repo_url, branch, repo_dir)
    if GITPYTHON_AVAILABLE:
        try:
            # Use optimized settings for large repos
            Repo.clone_from(
                repo_url,
                repo_dir,
                branch=branch,
                depth=1,
                config=[
                    "http.postBuffer=524288000",
                    "http.version=HTTP/1.1"
                ],
                allow_unsafe_options=True
            )
        except GitCommandError as e:
            raise RuntimeError(f"Clone failed: {e}") from e
    else:
        subprocess.run(
            [
                "git",
                "-c", "http.postBuffer=524288000",
                "-c", "http.version=HTTP/1.1",
                "clone",
                "--branch",
                branch,
                "--single-branch",
                "--depth",
                "1",
                repo_url,
                str(repo_dir),
            ],
            check=True,
        )
    logger.info("Clone completed successfully")
    return repo_dir


def ensure_latest_main(repo_path: Path, branch: str = REPO_BRANCH) -> None:
    """
    Fetch origin and reset to latest origin/<branch> so we have the most recent main
    before creating our branch and making changes. Reduces extra autogenerated file diffs.
    """
    logger.info("Fetching origin and resetting to latest %s", branch)
    if GITPYTHON_AVAILABLE:
        repo = Repo(repo_path)
        repo.remote("origin").fetch(branch)
        repo.git.reset("--hard", f"origin/{branch}")
    else:
        run_git_cmd(repo_path, "fetch", "origin", branch)
        run_git_cmd(repo_path, "reset", "--hard", f"origin/{branch}")
    logger.info("Repository is at latest %s", branch)


def create_branch(repo_path: Path) -> str:
    """
    Create a new unique branch: automation/rhoai-release-<timestamp>.
    Returns the branch name.
    """
    timestamp = datetime.utcnow().strftime("%Y%m%d-%H%M%S")
    branch_name = f"automation/rhoai-release-{timestamp}"
    logger.info("Creating branch: %s", branch_name)
    if GITPYTHON_AVAILABLE:
        repo = Repo(repo_path)
        repo.git.checkout("-b", branch_name)
    else:
        run_git_cmd(repo_path, "checkout", "-b", branch_name)
    logger.info("Branch created: %s", branch_name)
    return branch_name


def show_changes(repo_path: Path) -> None:
    """Print git status and diff of changes (no staging, no commit)."""
    logger.info("Showing changes (no staging or commit)")
    if GITPYTHON_AVAILABLE:
        repo = Repo(repo_path)
        status = repo.git.status()
        diff = repo.git.diff()
    else:
        status = run_git_cmd(repo_path, "status")
        try:
            diff = run_git_cmd(repo_path, "diff")
        except RuntimeError:
            diff = ""
    print("\n" + "=" * 60)
    print("DRY RUN - Changes made by automation (not staged, not committed)")
    print("=" * 60)
    print("\n--- Git status ---\n")
    print(status)
    print("\n--- Git diff (working tree) ---\n")
    print(diff if diff else "(no modified tracked files; see status for new/untracked files)")
    print("=" * 60)


def commit_and_push(
    repo_path: Path,
    new_version: str,
    branch_name: str,
    paths_to_add: Optional[List[str]] = None,
    dry_run: bool = False,
) -> None:
    """Commit changes and push branch to origin. If paths_to_add is set, only those paths are staged."""
    commit_message = f"Add Konflux release configuration for RHOAI v{new_version}"
    config_paths: List[str] = []
    autogen_paths: List[str] = []
    if paths_to_add:
        config_paths, autogen_paths = _partition_staging_paths(paths_to_add)
        logger.info(
            "Staging config paths: %s; auto-generated (rhoai-tenant subtree only): %s",
            config_paths,
            autogen_paths or ["(none)"],
        )
    else:
        logger.info("Staging all changes")
    if GITPYTHON_AVAILABLE:
        repo = Repo(repo_path)
        if paths_to_add:
            for p in config_paths:
                repo.git.add(p)
            for p in autogen_paths:
                rel = repo_path / p
                if not rel.exists():
                    logger.warning("Skip git add (path missing after build-manifests): %s", p)
                    continue
                repo.git.add(p)
        else:
            repo.git.add(A=True)
        if repo.is_dirty(untracked_files=True) or repo.untracked_files:
            repo.index.commit(commit_message)
            logger.info("Committed: %s", commit_message)
        else:
            logger.warning("No changes to commit")
            return
        if not dry_run:
            token = os.environ.get("KONFLUX_REPO_TOKEN")
            if not token:
                raise RuntimeError(
                    "KONFLUX_REPO_TOKEN is not set. Set it as a CI/CD variable (or env var) with push access to the target repo."
                )
            logger.info("Pushing branch to origin")
            origin = repo.remote("origin")
            # Use token in URL so push works in CI (avoids 'could not read Username')
            auth_url = REPO_URL.replace("https://", f"https://oauth2:{token}@", 1)
            origin.set_url(auth_url)
            origin.push(branch_name)
            logger.info("Pushed %s to origin", branch_name)
    else:
        if paths_to_add:
            if config_paths:
                run_git_cmd(repo_path, "add", *config_paths)
            for p in autogen_paths:
                rel = repo_path / p
                if not rel.exists():
                    logger.warning("Skip git add (path missing after build-manifests): %s", p)
                    continue
                run_git_cmd(repo_path, "add", p)
        else:
            run_git_cmd(repo_path, "add", "-A")
        try:
            run_git_cmd(repo_path, "diff", "--cached", "--quiet")
            logger.warning("No changes to commit")
            return
        except RuntimeError:
            pass
        run_git_cmd(repo_path, "commit", "-m", commit_message)
        logger.info("Committed: %s", commit_message)
        if not dry_run:
            token = os.environ.get("KONFLUX_REPO_TOKEN")
            if not token:
                raise RuntimeError(
                    "KONFLUX_REPO_TOKEN is not set. Set it as a CI/CD variable (or env var) with push access to the target repo."
                )
            auth_url = REPO_URL.replace("https://", f"https://oauth2:{token}@", 1)
            run_git_cmd(repo_path, "remote", "set-url", "origin", auth_url)
            logger.info("Pushing branch to origin")
            run_git_cmd(repo_path, "push", "-u", "origin", branch_name)
            logger.info("Pushed %s to origin", branch_name)
