#!/usr/bin/env python3
"""Generate a unified Conforma Violations Resolution Guide.

Combines outputs from the conforma-analyze workflow into a single markdown
document suitable for submission to the conforma-reporter repository.

Inputs:
  - violations.yaml (from parse_violations.py)
  - coverage.json (from violations_coverage.py)
  - CSV reports directory (for statistical analysis)
  - violation-catalog.yaml (for resolution guidance + fallback references)

Output: A unified markdown file with:
  1. Metadata header (generation date, source CSV link, etc.)
  2. Summary metrics
  3. Coverage table (verbatim from violations_coverage.py)
  4. Per-violation resolution guide (from catalog + fallbacks)
  5. Warnings becoming violations (if any)
  6. Statistical breakdown (from analyze_csv_report.py)

Usage:
    python3 skills/conforma-analyze/scripts/generate_resolution_guide.py \\
      --violations-yaml .work/20260610-143449/violations.yaml \\
      --coverage-json .work/20260610-143449/coverage.json \\
      --reports-dir .work/20260610-143449 \\
      --release rhoai-3.5-ea.2 \\
      --source-path "prod/release_day/conforma-violations-report.csv" \\
      --source-created-at "2026-06-10T05:19:05Z" \\
      --output .work/20260610-143449/conforma-violations-resolution-guide.md
"""

from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import _setup_env  # noqa: F401, E402

import yaml  # noqa: E402

sys.path.insert(0, str(Path(__file__).parent))
import analyze_csv_report as analysis  # noqa: E402

CONFORMA_REPORTER_REPO = "red-hat-data-services/conforma-reporter"


def _load_catalog(catalog_path: Path) -> dict:
    """Load the violation catalog YAML."""
    data = yaml.safe_load(catalog_path.read_text(encoding="utf-8"))
    return data


def _match_catalog_entry(rule_code: str, catalog: dict) -> dict | None:
    """Find a catalog violation entry matching the given rule code.

    Tries exact match on conforma_rule_codes first, then base_code prefix match.
    """
    base_code = rule_code.split(":")[0]
    violations = catalog.get("violations", [])

    for entry in violations:
        codes = entry.get("conforma_rule_codes", [])
        if rule_code in codes or base_code in codes:
            return entry

    for entry in violations:
        codes = entry.get("conforma_rule_codes", [])
        for code in codes:
            if base_code.startswith(code) or code.startswith(base_code):
                return entry

    return None


def _match_fallback_reference(rule_code: str, catalog: dict) -> dict | None:
    """Find the longest-matching fallback reference for a rule code."""
    base_code = rule_code.split(":")[0]
    fallbacks = catalog.get("fallback_references", [])

    best_match = None
    best_len = 0

    for fb in fallbacks:
        prefix = fb.get("code_prefix", "")
        if base_code.startswith(prefix) or base_code == prefix:
            if len(prefix) > best_len:
                best_match = fb
                best_len = len(prefix)

    return best_match


def _match_known_false_alert(rule_code: str, component: str, catalog: dict) -> dict | None:
    """Check if a violation matches a known false alert."""
    base_code = rule_code.split(":")[0]
    alerts = catalog.get("known_false_alerts", [])

    for alert in alerts:
        alert_codes = alert.get("conforma_rule_codes", [])
        if not alert_codes or base_code in alert_codes or rule_code in alert_codes:
            applies_to = alert.get("applies_to", "")
            if applies_to:
                import fnmatch

                if fnmatch.fnmatch(component, applies_to):
                    return alert
    return None


def _render_metadata_header(
    release: str,
    source_path: str,
    source_created_at: str,
) -> str:
    """Render the document metadata header."""
    now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    source_url = f"https://github.com/{CONFORMA_REPORTER_REPO}/blob/{release}/{source_path}"

    lines = [
        f"# Conforma Violations Resolution Guide: {release}",
        "",
        f"**Generated**: {now}",
        f"**Source CSV**: [{source_path}]({source_url})",
        f"**Source CSV generated**: {source_created_at}",
        "**Generated by**: aiops-infra conforma-analyze skill",
        "",
        "---",
        "",
    ]
    return "\n".join(lines)


def _render_summary(coverage_data: dict, analysis_result: analysis.AnalysisResult) -> str:
    """Render the summary metrics section."""
    summary = coverage_data.get("summary", {})
    lines = [
        "## Summary",
        "",
        "| Metric | Value |",
        "|--------|-------|",
        f"| Total violations | {analysis_result.total_violations:,} |",
        f"| Unique violation codes | {analysis_result.unique_codes} |",
        f"| Components affected | {analysis_result.unique_components} |",
        f"| Fully covered by exceptions | {summary.get('fully_covered', 0)} |",
        f"| Partially covered | {summary.get('partially_covered', 0)} |",
        f"| Not covered | {summary.get('not_covered', 0)} |",
    ]
    if analysis_result.upcoming_violations:
        lines.append(f"| Warnings becoming violations (21d) | {len(analysis_result.upcoming_violations)} |")
    lines.append("")
    return "\n".join(lines)


def _render_coverage_table(coverage_data: dict) -> str:
    """Render the coverage table section (verbatim from violations_coverage.py)."""
    md_table = coverage_data.get("markdown_table", "")
    lines = [
        "## Violations Coverage",
        "",
        md_table,
        "",
    ]
    return "\n".join(lines)


def _render_resolution_guide(coverage_data: dict, catalog: dict) -> str:
    """Render the per-violation resolution guide section."""
    violations = coverage_data.get("violations", [])
    component_owners = coverage_data.get("component_owners", {})
    lines = ["## Violation Resolution Guide", ""]

    for i, v in enumerate(violations, 1):
        rule = v["rule"]
        total_components = v["total_components"]

        owner_teams = set()
        for comp in v.get("uncovered_components", []) + v.get("covered_components", []):
            team = component_owners.get(comp)
            if team:
                owner_teams.add(team)
        teams_str = ", ".join(sorted(owner_teams)) if owner_teams else "unknown"

        lines.append(f"### {i}. `{rule}` — {total_components} components ({teams_str})")
        lines.append("")

        catalog_entry = _match_catalog_entry(rule, catalog)

        if catalog_entry:
            _render_cataloged_violation(lines, catalog_entry, v)
        else:
            fallback = _match_fallback_reference(rule, catalog)
            _render_uncataloged_violation(lines, v, fallback)

        # Known false alerts
        all_comps = v.get("uncovered_components", []) + v.get("covered_components", [])
        false_alert_comps = []
        for comp in all_comps:
            alert = _match_known_false_alert(rule, comp, catalog)
            if alert:
                false_alert_comps.append((comp, alert))

        if false_alert_comps:
            lines.append("**Known false alerts:**")
            for comp, alert in false_alert_comps:
                lines.append(f"- `{comp}`: {alert['title']} — {alert.get('condition', '')}")
            lines.append("")

        # Open MRs
        open_mrs = v.get("open_merge_requests", [])
        if open_mrs:
            lines.append("**Open MRs:**")
            for mr in open_mrs:
                iid = mr.get("iid", "?")
                url = mr.get("web_url", "")
                suggestion = mr.get("suggestion", "")
                covered = mr.get("covered", [])
                missing = mr.get("missing", [])
                if suggestion == "fully_covered":
                    lines.append(f"- [!{iid}]({url}) — covers all components")
                elif suggestion == "extend_mr":
                    lines.append(
                        f"- [!{iid}]({url}) — covers {len(covered)}/{total_components}. "
                        f"Missing: {', '.join(missing[:5])}"
                        + (f" +{len(missing) - 5} more" if len(missing) > 5 else "")
                    )
                else:
                    lines.append(f"- [!{iid}]({url})")
            lines.append("")

        # Open Jira
        open_jira = v.get("open_jira_tickets", [])
        if open_jira:
            lines.append("**Open Jira tickets:**")
            for ticket in open_jira:
                key = ticket.get("key", "")
                url = ticket.get("url", "")
                status = ticket.get("status", "")
                summary = ticket.get("summary", "")
                lines.append(f"- [{key}]({url}) ({status}): {summary[:80]}")
            lines.append("")

        # Slack threads
        open_slack = v.get("open_slack_threads", [])
        if open_slack:
            lines.append("**Slack threads:**")
            for thread in open_slack[:3]:
                permalink = thread.get("permalink", "")
                channel = thread.get("channel_name", "")
                date = thread.get("date", "")
                lines.append(f"- [#{channel}]({permalink}) ({date})")
            if len(open_slack) > 3:
                lines.append(f"- ... and {len(open_slack) - 3} more threads")
            lines.append("")

        lines.append("---")
        lines.append("")

    return "\n".join(lines)


def _render_cataloged_violation(lines: list[str], entry: dict, violation: dict) -> None:
    """Render resolution details for a violation with a catalog match."""
    classification = entry.get("classification", {})
    resolution_path = classification.get("resolution_path", "unknown")
    typical_owner = classification.get("typical_owner", "unknown")
    effort = classification.get("estimated_effort", "unknown")
    requires_rebuild = classification.get("requires_rebuild", False)

    lines.append(
        f"**Classification**: {resolution_path} | "
        f"Owner: {typical_owner} | "
        f"Effort: {effort} | "
        f"Requires rebuild: {'yes' if requires_rebuild else 'no'}"
    )
    lines.append("")

    fix_steps = entry.get("fix_steps", [])
    if fix_steps:
        lines.append("**Resolution:**")
        for j, step in enumerate(fix_steps, 1):
            action = step.get("action", "")
            ref = step.get("reference", "")
            where = step.get("where", "")
            line = f"{j}. {action}"
            if ref:
                line += f" — [docs]({ref})"
            if where:
                line += f" (in: {where})"
            lines.append(line)
        lines.append("")

    exception_ctx = entry.get("exception_context", {})
    when_to_exception = exception_ctx.get("when_to_exception", "")
    if when_to_exception:
        lines.append(f"**Exception only if**: {when_to_exception}")
        lines.append("")


def _render_uncataloged_violation(lines: list[str], violation: dict, fallback: dict | None) -> None:
    """Render resolution details for a violation without a catalog match."""
    title = violation.get("title", "")

    lines.append("**Note**: Not in violation catalog — using fallback references.")
    lines.append("")

    if title:
        lines.append(f"**From report**: {title}")
        lines.append("")

    if fallback:
        doc_urls = fallback.get("doc_urls", [])
        guidance = fallback.get("guidance", "")

        if doc_urls:
            lines.append("**References:**")
            for url in doc_urls:
                lines.append(f"- [{url}]({url})")
            lines.append("")

        if guidance:
            lines.append(f"**Guidance**: {guidance}")
            lines.append("")
    else:
        lines.append(
            "**Guidance**: No resolution guidance available. Investigate the build logs and Konflux documentation."
        )
        lines.append("")


def _render_warnings_section(analysis_result: analysis.AnalysisResult, component_owners: dict) -> str:
    """Render warnings becoming violations section."""
    if not analysis_result.upcoming_violations:
        return ""

    lines = [
        "## Warnings Becoming Violations",
        "",
        f"**{len(analysis_result.upcoming_violations)}** current warnings will become "
        "enforced violations once their enforcement date passes.",
        "",
        "| Code | Count | Deadline | Days Left | Components |",
        "|------|-------|----------|-----------|------------|",
    ]

    for code, info in sorted(
        analysis_result.upcoming_by_code.items(),
        key=lambda x: x[1]["min_days_remaining"],
    ):
        days = info["min_days_remaining"]
        urgency = "**OVERDUE**" if days == 0 else str(days)
        comps = ", ".join(f"`{c}`" for c in info["affected_components"][:5])
        if len(info["affected_components"]) > 5:
            comps += f" +{len(info['affected_components']) - 5} more"
        lines.append(f"| `{code}` | {info['count']} | {info['earliest_effective_on']} | {urgency} | {comps} |")

    lines.append("")
    return "\n".join(lines)


def _render_statistical_breakdown(
    analysis_result: analysis.AnalysisResult,
    component_owners: dict[str, str | None],
) -> str:
    """Render the statistical breakdown section using analyze_csv_report's format_markdown."""
    md = analysis.format_markdown(analysis_result, component_owners)
    md = md.replace("# Conforma Violations Analysis", "## Statistical Breakdown", 1)
    return md


def generate_resolution_guide(
    violations_yaml_path: str,
    coverage_json_path: str,
    reports_dir: str,
    catalog_path: str,
    release: str,
    source_path: str,
    source_created_at: str,
) -> str:
    """Generate the full resolution guide markdown content."""
    violations_yaml = Path(violations_yaml_path)
    coverage_json = Path(coverage_json_path)
    reports = Path(reports_dir)
    catalog_file = Path(catalog_path)

    if not violations_yaml.exists():
        raise FileNotFoundError(f"Violations YAML not found: {violations_yaml}")
    if not coverage_json.exists():
        raise FileNotFoundError(f"Coverage JSON not found: {coverage_json}")
    if not reports.is_dir():
        raise FileNotFoundError(f"Reports directory not found: {reports}")
    if not catalog_file.exists():
        raise FileNotFoundError(f"Violation catalog not found: {catalog_file}")

    coverage_data = json.loads(coverage_json.read_text(encoding="utf-8"))
    catalog = _load_catalog(catalog_file)

    # Load component ownership from violations YAML
    viol_data = yaml.safe_load(violations_yaml.read_text(encoding="utf-8"))
    component_owners: dict[str, str | None] = {}
    by_component = viol_data.get("violation_data", {}).get("violations_by_component", {})
    for comp, info in by_component.items():
        jc = info.get("jira_component")
        if jc is not None:
            component_owners[comp] = jc

    # Run statistical analysis
    records = analysis.load_reports_dir(reports)
    warnings = analysis.load_warnings_dir(reports)
    analysis_result = analysis.analyze(records, upcoming=warnings)

    # Assemble sections
    sections = [
        _render_metadata_header(release, source_path, source_created_at),
        _render_summary(coverage_data, analysis_result),
        _render_coverage_table(coverage_data),
        _render_resolution_guide(coverage_data, catalog),
        _render_warnings_section(analysis_result, component_owners),
        _render_statistical_breakdown(analysis_result, component_owners),
    ]

    return "\n".join(s for s in sections if s)


def _find_default_catalog() -> Path:
    """Find the default violation catalog relative to this script."""
    here = Path(__file__).resolve().parent
    # scripts/ -> conforma-analyze/ -> skills/ -> repo/skills/references/
    candidate = here.parent.parent / "references" / "violation-catalog.yaml"
    if candidate.exists():
        return candidate
    # Try from repo root
    repo_root = here.parent.parent.parent
    candidate2 = repo_root / "skills" / "references" / "violation-catalog.yaml"
    if candidate2.exists():
        return candidate2
    raise FileNotFoundError("Cannot find violation-catalog.yaml. Use --catalog to specify its path.")


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate a unified Conforma Violations Resolution Guide")
    parser.add_argument("--violations-yaml", required=True, help="Path to parsed violations YAML")
    parser.add_argument("--coverage-json", required=True, help="Path to coverage check JSON output")
    parser.add_argument("--reports-dir", required=True, help="Directory containing CSV reports")
    parser.add_argument(
        "--catalog",
        default=None,
        help="Path to violation-catalog.yaml (default: auto-detect)",
    )
    parser.add_argument("--release", required=True, help="Release name (e.g. rhoai-3.5-ea.2)")
    parser.add_argument(
        "--source-path",
        required=True,
        help="CSV source path in the repo (e.g. prod/release_day/conforma-violations-report.csv)",
    )
    parser.add_argument(
        "--source-created-at",
        required=True,
        help="When the source CSV was generated (ISO timestamp)",
    )
    parser.add_argument("--output", required=True, help="Output file path")
    args = parser.parse_args()

    catalog_path = args.catalog or str(_find_default_catalog())

    try:
        content = generate_resolution_guide(
            violations_yaml_path=args.violations_yaml,
            coverage_json_path=args.coverage_json,
            reports_dir=args.reports_dir,
            catalog_path=catalog_path,
            release=args.release,
            source_path=args.source_path,
            source_created_at=args.source_created_at,
        )
    except FileNotFoundError as e:
        print(f"ERROR: {e}", file=sys.stderr)
        return 1

    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(content, encoding="utf-8")
    print(f"Resolution guide written to {output_path}", file=sys.stderr)
    print(json.dumps({"output": str(output_path), "release": args.release}))
    return 0


if __name__ == "__main__":
    sys.exit(main())
