#!/usr/bin/env python3
"""Create a GitLab MR in releng/konflux-release-data with the exception YAML.

Workflow:
1. Shallow clone the repo (or use existing clone)
2. Determine target file based on component type + environment
3. Generate and append the exception YAML block
4. Create branch, commit, push, and create MR via glab
"""

from __future__ import annotations

import argparse
import getpass
import json
import platform
import re
import subprocess
import sys
import tempfile
from pathlib import Path

GITLAB_HOST = "gitlab.cee.redhat.com"
GITLAB_PROJECT = "releng/konflux-release-data"
DEFAULT_BRANCH = "main"
PROVENANCE_REPO = "opendatahub-io/ai-helpers"
PROVENANCE_SKILL = "conforma-exception-create-ai-skill"


def _build_commit_message(
    rule: str,
    components: list[str],
    rhoai_version: str,
    effective_until: str,
    rhoaieng_url: str | None = None,
    reference_url: str | None = None,
    spreadsheet_url: str | None = None,
    target_file: str | None = None,
) -> str:
    """Build a structured, multi-line commit message with provenance."""
    subject = f"Add conforma exception: {rule} ({rhoai_version})"

    lines = [
        subject,
        "",
        "Exception details:",
        f"  Rule: {rule}",
        f"  RHOAI version: {rhoai_version}",
        f"  Effective until: {effective_until}",
        f"  Components: {', '.join(components)}",
    ]

    if target_file:
        lines.append(f"  Policy file: {target_file}")

    lines.append("")

    if rhoaieng_url:
        lines.append(f"RHOAIENG: {rhoaieng_url}")
    if reference_url:
        lines.append(f"Reference: {reference_url}")
    if spreadsheet_url:
        lines.append(f"Spreadsheet: {spreadsheet_url}")

    if rhoaieng_url or reference_url or spreadsheet_url:
        lines.append("")

    lines.extend([
        "---",
        f"Generated by: {PROVENANCE_SKILL}",
        f"Source: https://github.com/{PROVENANCE_REPO}",
        f"User: {getpass.getuser()}@{platform.node()}",
    ])

    return "\n".join(lines)


def _build_mr_body(
    rule: str,
    components: list[str],
    rhoai_version: str,
    effective_until: str,
    rhoaieng_url: str | None = None,
    reference_url: str | None = None,
    spreadsheet_url: str | None = None,
    target_file: str | None = None,
) -> str:
    """Build a markdown-formatted MR description for GitLab rendering."""
    lines = [
        f"## Exception: `{rule}` for `{rhoai_version}`",
        "",
        "| Field | Value |",
        "|-------|-------|",
        f"| **Rule** | `{rule}` |",
        f"| **RHOAI version** | `{rhoai_version}` |",
        f"| **Effective until** | `{effective_until}` |",
        f"| **Policy file** | `{target_file or 'N/A'}` |",
        "",
        "### Components",
        "",
    ]
    for comp in components:
        lines.append(f"- `{comp}`")

    lines.append("")

    if rhoaieng_url or reference_url or spreadsheet_url:
        lines.append("### References")
        lines.append("")
        if rhoaieng_url:
            lines.append(f"- **RHOAIENG**: {rhoaieng_url}")
        if reference_url:
            lines.append(f"- **PSX/Reference**: {reference_url}")
        if spreadsheet_url:
            lines.append(f"- **Spreadsheet**: {spreadsheet_url}")
        lines.append("")

    lines.extend([
        "---",
        "",
        f"*Generated by `{PROVENANCE_SKILL}` | "
        f"[source](https://github.com/{PROVENANCE_REPO}) | "
        f"`{getpass.getuser()}@{platform.node()}`*",
    ])

    return "\n".join(lines)


def _build_mr_title(rule: str, rhoai_version: str, vendor_tag: str | None = None) -> str:
    """Build the MR title, including vendor tag if provided."""
    title = f"[RHOAI] Conforma exception: {rule} for {rhoai_version}"
    if vendor_tag:
        title = f"[{vendor_tag}] {title}"
    return title


def _get_gitlab_token() -> str | None:
    """Retrieve the glab auth token for GITLAB_HOST."""
    result = subprocess.run(
        ["glab", "config", "get", "token", "--host", GITLAB_HOST],
        capture_output=True,
        text=True,
        timeout=10,
    )
    if result.returncode == 0 and result.stdout.strip():
        return result.stdout.strip()
    return None


def _get_authenticated_repo_url(project: str = GITLAB_PROJECT) -> str:
    """Build a clone URL with embedded token for non-interactive git."""
    token = _get_gitlab_token()
    if token:
        return f"https://oauth2:{token}@{GITLAB_HOST}/{project}.git"
    return f"https://{GITLAB_HOST}/{project}.git"


_EC_POLICY_DIR = "config/stone-prod-p02.hjvn.p1/product/EnterpriseContractPolicy"

POLICY_PATHS = {
    ("registry", "prod"): f"{_EC_POLICY_DIR}/registry-rhoai-prod.yaml",
    ("registry", "stage"): f"{_EC_POLICY_DIR}/registry-rhoai-stage.yaml",
    ("fbc", "prod"): f"{_EC_POLICY_DIR}/fbc-rhoai-prod.yaml",
    ("fbc", "stage"): f"{_EC_POLICY_DIR}/fbc-rhoai-stage.yaml",
}

SELF_SERVICE_PATHS = {
    ("fbc", "prod"): "exceptions/fbc-rhoai-prod.yaml",
    ("fbc", "stage"): "exceptions/fbc-rhoai-stage.yaml",
    ("registry", "prod"): "exceptions/registry-rhoai-prod.yaml",
    ("registry", "stage"): "exceptions/registry-rhoai-stage.yaml",
}


def detect_component_type(components: list[str]) -> str:
    """Detect if components are FBC or registry type."""
    for comp in components:
        if "fbc" in comp.lower():
            return "fbc"
    return "registry"


def get_target_file(component_type: str, environment: str, is_self_service: bool) -> str:
    """Determine the target policy file path."""
    key = (component_type, environment)
    if is_self_service:
        return SELF_SERVICE_PATHS.get(key, SELF_SERVICE_PATHS[("fbc", "prod")])
    return POLICY_PATHS.get(key, POLICY_PATHS[("registry", "prod")])


def generate_exception_yaml(
    rule: str,
    components: list[str],
    effective_until: str,
    reference_url: str,
    rhoaieng_url: str | None,
    rhoai_version: str,
    is_self_service: bool,
    is_weekday_restriction: bool = False,
    image_ref: str | None = None,
    reference_title: str | None = None,
    spreadsheet_url: str | None = None,
) -> str:
    """Generate the YAML exception block to append.

    Components must be Konflux component names (with -vX-Y suffix), NOT container
    image names (which end in -rhel9/-ubi9). validate_inputs.py enforces this.
    """
    if is_self_service and is_weekday_restriction and image_ref:
        return f"- value: {rule}\n  imageRef: {image_ref}\n"

    if is_self_service:
        lines = [f"- value: {rule}"]
        lines.append("  componentNames:")
        for comp in components:
            lines.append(f"    - {comp}")
        if effective_until:
            lines.append(f'  effectiveUntil: "{effective_until}"')
        return "\n".join(lines) + "\n"

    indent = "          "
    lines = []
    if rhoaieng_url:
        lines.append(f"{indent}# {rhoaieng_url}")
    lines.append(f"{indent}# impacted versions: {rhoai_version}")
    if spreadsheet_url:
        lines.append(f"{indent}# spreadsheet: {spreadsheet_url}")
    lines.append(f"{indent}- value: {rule}")
    lines.append(f"{indent}  componentNames:")
    for comp in components:
        lines.append(f"{indent}    - {comp}")
    lines.append(f'{indent}  effectiveUntil: "{effective_until}"')
    if reference_title:
        lines.append(f"{indent}  reference: {reference_url}  # {reference_title}")
    else:
        lines.append(f"{indent}  reference: {reference_url}")
    return "\n".join(lines) + "\n"


def append_to_policy_file(file_path: Path, yaml_block: str, is_self_service: bool) -> None:
    """Append the exception block to the target file."""
    content = file_path.read_text(encoding="utf-8")

    if is_self_service:
        if content.rstrip().endswith("---"):
            content = content.rstrip() + "\n"
        content += yaml_block
    else:
        content = content.rstrip() + "\n" + yaml_block

    file_path.write_text(content, encoding="utf-8")


def create_mr(
    rule: str,
    components: list[str],
    effective_until: str,
    reference_url: str,
    rhoaieng_url: str | None,
    rhoai_version: str,
    environment: str,
    is_self_service: bool,
    is_weekday_restriction: bool = False,
    image_ref: str | None = None,
    reference_title: str | None = None,
    spreadsheet_url: str | None = None,
    vendor_tag: str | None = None,
    dry_run: bool = False,
) -> dict:
    """Clone repo, append exception, create MR."""
    component_type = detect_component_type(components)
    target_file = get_target_file(component_type, environment, is_self_service)

    yaml_block = generate_exception_yaml(
        rule=rule,
        components=components,
        effective_until=effective_until,
        reference_url=reference_url,
        rhoaieng_url=rhoaieng_url,
        rhoai_version=rhoai_version,
        is_self_service=is_self_service,
        is_weekday_restriction=is_weekday_restriction,
        image_ref=image_ref,
        reference_title=reference_title,
        spreadsheet_url=spreadsheet_url,
    )

    if dry_run:
        return {
            "status": "dry_run",
            "target_file": target_file,
            "yaml_block": yaml_block,
            "component_type": component_type,
            "mr_url": None,
        }

    workdir = Path(tempfile.mkdtemp(prefix="conforma-mr-"))
    try:
        clone_dest = str(workdir / "repo")
        repo_url = _get_authenticated_repo_url()
        _run_git(
            [
                "git",
                "clone",
                "--depth=1",
                "--branch",
                DEFAULT_BRANCH,
                repo_url,
                clone_dest,
            ],
            timeout=300,
        )
        repo_dir = workdir / "repo"

        branch_name = _make_branch_name(rule, rhoai_version, components)
        _run_git(["git", "checkout", "-b", branch_name], cwd=repo_dir)

        policy_file = repo_dir / target_file
        if not policy_file.exists():
            return {
                "status": "failed",
                "error": f"Target file not found: {target_file}",
                "target_file": target_file,
                "mr_url": None,
            }

        append_to_policy_file(policy_file, yaml_block, is_self_service)

        commit_msg = _build_commit_message(
            rule=rule,
            components=components,
            rhoai_version=rhoai_version,
            effective_until=effective_until,
            rhoaieng_url=rhoaieng_url,
            reference_url=reference_url,
            spreadsheet_url=spreadsheet_url,
            target_file=target_file,
        )

        _run_git(["git", "add", target_file], cwd=repo_dir)
        _run_git(["git", "commit", "-m", commit_msg], cwd=repo_dir)
        push_result = subprocess.run(
            ["git", "push", "-u", "origin", branch_name],
            capture_output=True,
            text=True,
            timeout=60,
            cwd=repo_dir,
        )

        use_fork = False
        if push_result.returncode != 0:
            fork_url = _ensure_fork(repo_dir)
            if not fork_url:
                return {
                    "status": "failed",
                    "error": (
                        f"Push failed and fork creation failed: {push_result.stderr.strip()}"
                    ),
                    "target_file": target_file,
                    "branch": branch_name,
                    "mr_url": None,
                }
            _run_git(["git", "remote", "add", "fork", fork_url], cwd=repo_dir)
            _run_git(["git", "push", "-u", "fork", branch_name], cwd=repo_dir)
            use_fork = True

        mr_title = _build_mr_title(rule, rhoai_version, vendor_tag)
        mr_body = _build_mr_body(
            rule=rule, components=components, rhoai_version=rhoai_version,
            effective_until=effective_until, rhoaieng_url=rhoaieng_url,
            reference_url=reference_url, spreadsheet_url=spreadsheet_url,
            target_file=target_file,
        )
        mr_create_args = [
            "mr",
            "create",
            "--title",
            mr_title,
            "--description",
            mr_body,
            "--target-branch",
            DEFAULT_BRANCH,
            "--remove-source-branch",
            "-R",
            f"{GITLAB_HOST}/{GITLAB_PROJECT}",
        ]
        if use_fork:
            mr_create_args.extend(["--head", branch_name])

        mr_result = subprocess.run(
            ["glab", *mr_create_args],
            capture_output=True,
            text=True,
            timeout=30,
            cwd=repo_dir,
        )

        if mr_result.returncode != 0:
            return {
                "status": "failed",
                "error": mr_result.stderr.strip() or mr_result.stdout.strip(),
                "target_file": target_file,
                "branch": branch_name,
                "mr_url": None,
                "use_fork": use_fork,
            }

        mr_url = _extract_mr_url(mr_result.stdout + mr_result.stderr)
        return {
            "status": "created",
            "target_file": target_file,
            "branch": branch_name,
            "mr_url": mr_url,
            "yaml_block": yaml_block,
            "component_type": component_type,
            "use_fork": use_fork,
        }
    except subprocess.CalledProcessError as exc:
        return {
            "status": "failed",
            "error": f"Git operation failed: {exc.stderr or exc.stdout}",
            "target_file": target_file,
            "mr_url": None,
        }
    finally:
        import shutil

        shutil.rmtree(workdir, ignore_errors=True)


def update_mr(
    branch_name: str,
    rule: str,
    components: list[str],
    effective_until: str,
    reference_url: str,
    rhoaieng_url: str | None,
    rhoai_version: str,
    environment: str,
    is_self_service: bool,
    is_weekday_restriction: bool = False,
    image_ref: str | None = None,
    reference_title: str | None = None,
    spreadsheet_url: str | None = None,
    vendor_tag: str | None = None,
    dry_run: bool = False,
) -> dict:
    """Update an existing MR branch by recreating it from current main.

    Always clones from main first to maintain proper merge-base ancestry,
    then creates the branch, applies the exception, and force-pushes.
    This avoids disconnected-history issues that cause GitLab to show
    hundreds of unrelated file changes in the MR diff.
    """
    component_type = detect_component_type(components)
    target_file = get_target_file(component_type, environment, is_self_service)

    yaml_block = generate_exception_yaml(
        rule=rule,
        components=components,
        effective_until=effective_until,
        reference_url=reference_url,
        rhoaieng_url=rhoaieng_url,
        rhoai_version=rhoai_version,
        is_self_service=is_self_service,
        is_weekday_restriction=is_weekday_restriction,
        image_ref=image_ref,
        reference_title=reference_title,
        spreadsheet_url=spreadsheet_url,
    )

    if dry_run:
        return {
            "status": "dry_run",
            "target_file": target_file,
            "yaml_block": yaml_block,
            "branch": branch_name,
            "component_type": component_type,
            "mr_url": None,
        }

    workdir = Path(tempfile.mkdtemp(prefix="conforma-mr-update-"))
    try:
        clone_dest = str(workdir / "repo")
        repo_url = _get_authenticated_repo_url()
        _run_git(
            [
                "git",
                "clone",
                "--depth=1",
                "--branch",
                DEFAULT_BRANCH,
                repo_url,
                clone_dest,
            ],
            timeout=300,
        )
        repo_dir = workdir / "repo"

        _run_git(["git", "checkout", "-b", branch_name], cwd=repo_dir)

        policy_file = repo_dir / target_file
        if not policy_file.exists():
            return {
                "status": "failed",
                "error": f"Target file not found: {target_file}",
                "target_file": target_file,
                "mr_url": None,
            }

        append_to_policy_file(policy_file, yaml_block, is_self_service)

        commit_msg = _build_commit_message(
            rule=rule,
            components=components,
            rhoai_version=rhoai_version,
            effective_until=effective_until,
            rhoaieng_url=rhoaieng_url,
            reference_url=reference_url,
            spreadsheet_url=spreadsheet_url,
            target_file=target_file,
        )

        _run_git(["git", "add", target_file], cwd=repo_dir)
        _run_git(["git", "commit", "-m", commit_msg], cwd=repo_dir)

        push_result = subprocess.run(
            ["git", "push", "--force", "origin", f"HEAD:{branch_name}"],
            capture_output=True,
            text=True,
            timeout=60,
            cwd=repo_dir,
        )
        if push_result.returncode != 0:
            return {
                "status": "failed",
                "error": f"Force push failed: {push_result.stderr.strip()}",
                "target_file": target_file,
                "branch": branch_name,
                "mr_url": None,
            }

        mr_url = _extract_mr_url(push_result.stdout + push_result.stderr)
        return {
            "status": "updated",
            "target_file": target_file,
            "branch": branch_name,
            "mr_url": mr_url,
            "yaml_block": yaml_block,
            "component_type": component_type,
        }
    except subprocess.CalledProcessError as exc:
        return {
            "status": "failed",
            "error": f"Git operation failed: {exc.stderr or exc.stdout}",
            "target_file": target_file,
            "mr_url": None,
        }
    finally:
        import shutil

        shutil.rmtree(workdir, ignore_errors=True)


def _ensure_fork(repo_dir: Path) -> str | None:
    """Create or get existing fork of the upstream project, return authenticated URL."""
    result = subprocess.run(
        [
            "glab",
            "repo",
            "fork",
            GITLAB_PROJECT,
            "--hostname",
            GITLAB_HOST,
            "--clone=false",
        ],
        capture_output=True,
        text=True,
        timeout=30,
        cwd=repo_dir,
    )
    output = result.stdout + result.stderr
    fork_project = _extract_fork_project(output)
    if fork_project:
        return _get_authenticated_repo_url(fork_project)
    if "already exists" in output.lower():
        user_result = subprocess.run(
            ["glab", "auth", "status", "--hostname", GITLAB_HOST],
            capture_output=True,
            text=True,
            timeout=10,
        )
        user_match = re.search(r"Logged in .* as (\S+)", user_result.stdout + user_result.stderr)
        if user_match:
            username = user_match.group(1)
            project_name = GITLAB_PROJECT.split("/")[-1]
            return _get_authenticated_repo_url(f"{username}/{project_name}")
    return None


def _extract_fork_project(output: str) -> str | None:
    """Extract fork project path from glab fork output."""
    match = re.search(rf"{re.escape(GITLAB_HOST)}/([^\s]+?)(?:\.git)?(?:\s|$)", output)
    if match:
        return match.group(1)
    return None


def _make_branch_name(rule: str, version: str, components: list[str]) -> str:
    """Generate a descriptive branch name."""
    rule_short = rule.replace(".", "-").replace(":", "-")[:30]
    comp_short = components[0][:20] if components else "unknown"
    version_short = version.replace("rhoai-", "")
    return f"conforma-exception/{rule_short}/{comp_short}-{version_short}"


def _run_git(
    cmd: list[str], cwd: Path | None = None, timeout: int = 60
) -> subprocess.CompletedProcess:
    """Run a git command, raising on failure."""
    result = subprocess.run(cmd, capture_output=True, text=True, timeout=timeout, cwd=cwd)
    if result.returncode != 0:
        raise subprocess.CalledProcessError(result.returncode, cmd, result.stdout, result.stderr)
    return result


def _extract_mr_url(output: str) -> str | None:
    """Extract MR URL from glab output."""
    match = re.search(r"(https://[^\s]+merge_requests/\d+)", output)
    return match.group(1) if match else None


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Create GitLab MR for Conforma exception")
    parser.add_argument("--rule", required=True)
    parser.add_argument("--components", required=True, help="Comma-separated")
    parser.add_argument("--effective-until", required=True)
    parser.add_argument("--reference-url", required=True, help="PSX/OCPEXCEPT ticket URL")
    parser.add_argument("--reference-title", default=None, help="PSX/OCPEXCEPT ticket title")
    parser.add_argument("--rhoaieng-url", default=None)
    parser.add_argument("--rhoai-version", required=True)
    parser.add_argument("--environment", default="prod", choices=["prod", "stage"])
    parser.add_argument(
        "--spreadsheet-url", default=None, help="Tracking spreadsheet URL (YAML comment)"
    )
    parser.add_argument("--self-service", action="store_true")
    parser.add_argument("--image-ref", default=None, help="SHA digest for weekday_restriction")
    parser.add_argument(
        "--vendor-tag", default=None,
        help="Vendor/distinguisher tag prepended to MR title (e.g. AMD, Intel)",
    )
    parser.add_argument("--update-mr", default=None, help="Existing MR branch to update")
    parser.add_argument("--dry-run", action="store_true")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    components = [c.strip() for c in args.components.split(",")]
    is_weekday = args.rule == "schedule.weekday_restriction"

    if args.update_mr:
        result = update_mr(
            branch_name=args.update_mr,
            rule=args.rule,
            components=components,
            effective_until=args.effective_until,
            reference_url=args.reference_url,
            rhoaieng_url=args.rhoaieng_url,
            rhoai_version=args.rhoai_version,
            environment=args.environment,
            is_self_service=args.self_service,
            is_weekday_restriction=is_weekday,
            image_ref=args.image_ref,
            reference_title=args.reference_title,
            spreadsheet_url=args.spreadsheet_url,
            vendor_tag=args.vendor_tag,
            dry_run=args.dry_run,
        )
    else:
        result = create_mr(
            rule=args.rule,
            components=components,
            effective_until=args.effective_until,
            reference_url=args.reference_url,
            rhoaieng_url=args.rhoaieng_url,
            rhoai_version=args.rhoai_version,
            environment=args.environment,
            is_self_service=args.self_service,
            is_weekday_restriction=is_weekday,
            image_ref=args.image_ref,
            reference_title=args.reference_title,
            spreadsheet_url=args.spreadsheet_url,
            vendor_tag=args.vendor_tag,
            dry_run=args.dry_run,
        )
    print(json.dumps(result, indent=2))
    return 0 if result["status"] in ("created", "updated", "dry_run") else 1


if __name__ == "__main__":
    sys.exit(main())
